// components/object/delete/task/item.vue
<template>
  <div class="flex flex-col gap-1">
    <div class="flex items-center justify-between gap-3">
      <div class="truncate text-sm font-medium text-foreground">{{ task.key }}</div>
      <Button variant="ghost" size="sm" class="h-auto px-2 text-xs" @click="handleDeleteTask">
        {{ t('Delete Record') }}
      </Button>
    </div>
    <Progress :model-value="task.progress" class="h-[2px]" />
    <div class="flex items-center justify-between text-muted-foreground">
      <div></div>
      <div class="text-muted-foreground">
        <span v-if="task.status === 'pending'">{{ t('Waiting') }}</span>
        <span v-else-if="task.status === 'deleting'">{{ t('Deleting') }}</span>
        <span v-else-if="task.status === 'completed'">{{ t('Success Status') }}</span>
        <span v-else-if="task.status === 'failed'">{{ t('Failed Status') }}</span>
        <span v-else-if="task.status === 'canceled'">{{ t('Canceled') }}</span>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { Button } from '@/components/ui/button'

import Progress from '@/components/ui/progress/Progress.vue'
import type { DeleteTask } from '~/lib/delete-task-manager'
import { useDeleteTaskManagerStore } from '~/store/delete-tasks'

const { t } = useI18n()
const store = useDeleteTaskManagerStore()

const props = defineProps<{ task: DeleteTask }>()

const handleDeleteTask = () => {
  store.removeTask(props.task.id)
}
</script>

// components/tasks/item.tsx
"use client"

import * as React from "react"
import { useTranslation } from "react-i18next"
import { RiDeleteBinLine } from "@remixicon/react"
import { Button } from "@/components/ui/button"
import { Progress } from "@/components/ui/progress"
import { useTaskManager } from "@/contexts/task-context"
import type { AnyTask } from "@/contexts/task-context"

interface TaskItemProps {
  task: AnyTask
}

const statusMap: Record<string, string> = {
  pending: "waiting",
  running: "in progress",
  completed: "success",
  failed: "failed",
  paused: "paused",
  canceled: "canceled",
}

export function TaskItem({ task }: TaskItemProps) {
  const { t } = useTranslation()
  const taskManager = useTaskManager()

  const statusKey = statusMap[task.status] ?? "in progress"
  const statusText = `${t(task.actionLabel)}${t(statusKey)}`

  return (
    <div className="flex flex-col gap-1">
      <div className="flex items-center justify-between gap-3 group">
        <div className="min-w-0 flex-1 truncate text-sm font-medium text-foreground">
          {task.displayName}
        </div>
        <Button
          variant="ghost"
          size="sm"
          className="h-auto shrink-0 px-2 text-xs opacity-0 group-hover:opacity-100"
          onClick={() => taskManager.removeTask(task.id)}
        >
          <RiDeleteBinLine className="size-4 text-red-500" />
        </Button>
      </div>
      <Progress value={task.progress} className="h-[2px]" />
      <div className="flex items-center justify-between text-xs text-muted-foreground">
        <div>{task.subInfo}</div>
        <div>{statusText}</div>
      </div>
    </div>
  )
}
