// components/user/edit-form.vue
<template>
  <Modal v-model="visible" :title="user.accessKey || t('Account')" size="lg" :close-on-backdrop="false">
    <div class="space-y-4">
      <div class="flex items-center justify-start gap-2 rounded-md border px-3 py-2">
        <span class="text-sm text-muted-foreground">{{ t('Status') }}</span>
        <Switch v-model="statusBoolean" />
        <Button variant="outline" @click="handleChangeSecretKey" class="ml-auto">
          <Icon name="ri:key-2-line" class="size-4" />
          <span>{{ t('Change Secret Key') }}</span>
        </Button>
      </div>

      <Tabs v-model="activeTab" class="flex flex-col gap-4">
        <TabsList class="w-full justify-start overflow-x-auto">
          <TabsTrigger value="groups">{{ t('Groups') }}</TabsTrigger>
          <TabsTrigger value="policy">{{ t('Policies') }}</TabsTrigger>
          <TabsTrigger value="account">{{ t('Account') }}</TabsTrigger>
        </TabsList>

        <TabsContent value="groups" class="mt-0">
          <user-groups :user="user" @search="refreshUser" />
        </TabsContent>
        <TabsContent value="policy" class="mt-0">
          <user-policies :user="user" @search="refreshUser" />
        </TabsContent>
        <TabsContent value="account" class="mt-0">
          <user-account :user="user" @search="refreshUser" @notice="noticeDialog" />
        </TabsContent>
      </Tabs>

      <user-notice ref="noticeRef" @search="refreshUser" />
    </div>
  </Modal>

  <user-change-secret-key v-model:visible="changeSecretKeyVisible" :access-key="user.accessKey" />
</template>

<script setup lang="ts">
import { Switch } from '@/components/ui/switch'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { computed, ref } from 'vue'
import { useI18n } from 'vue-i18n'
import Modal from '~/components/modal.vue'

const { t } = useI18n()
const visible = ref(false)
const activeTab = ref('groups')
const changeSecretKeyVisible = ref(false)
const { getUser, changeUserStatus } = useUsers()

interface UserInfo {
  accessKey: string
  memberOf: string[]
  policy: string[]
  status: string
}

const user = ref<UserInfo>({
  accessKey: '',
  memberOf: [],
  policy: [],
  status: 'enabled',
})

const statusBoolean = computed({
  get: () => user.value.status === 'enabled',
  set: async value => {
    const nextStatus = value ? 'enabled' : 'disabled'
    if (user.value.accessKey) {
      await changeUserStatus(user.value.accessKey, {
        accessKey: user.value.accessKey,
        status: nextStatus,
      })
      await refreshUser()
    }
  },
})

const refreshUser = async () => {
  if (!user.value.accessKey) return
  const latest = await getUser(user.value.accessKey)
  user.value = {
    accessKey: user.value.accessKey,
    memberOf: latest.memberOf ?? [],
    policy: latest.policyName?.split(',') ?? [],
    status: latest.status ?? 'enabled',
  }
}

const noticeRef = ref()
const noticeDialog = (data: any) => {
  noticeRef.value?.openDialog(data)
}

const handleChangeSecretKey = () => {
  visible.value = false
  changeSecretKeyVisible.value = true
}

async function openDialog(row: any) {
  user.value = {
    accessKey: row.accessKey,
    memberOf: row.memberOf ?? [],
    policy: row.policy ?? [],
    status: row.status ?? 'enabled',
  }
  activeTab.value = 'groups'
  visible.value = true
  await refreshUser()
}

defineExpose({
  openDialog,
})
</script>

// components/user/edit-form.tsx
"use client"

import * as React from "react"
import { useTranslation } from "react-i18next"
import { Switch } from "@/components/ui/switch"
import { Button } from "@/components/ui/button"
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { useUsers } from "@/hooks/use-users"

interface UserRow {
  accessKey: string
  policyName?: string
  status?: string
  memberOf?: string[]
  updatedAt?: string
  [key: string]: unknown
}

interface UserEditFormProps {
  open: boolean
  onOpenChange: (open: boolean) => void
  row: UserRow | null
  onSuccess: () => void
}

export function UserEditForm({ open, onOpenChange, row, onSuccess }: UserEditFormProps) {
  const { t } = useTranslation()
  const { getUser, changeUserStatus } = useUsers()

  const [user, setUser] = React.useState<{
    accessKey: string
    memberOf: string[]
    policy: string[]
    status: string
  }>({
    accessKey: "",
    memberOf: [],
    policy: [],
    status: "enabled",
  })
  const [loading, setLoading] = React.useState(false)

  const statusBoolean = user.status === "enabled"

  const refreshUser = React.useCallback(async () => {
    if (!user.accessKey) return
    try {
      const latest = (await getUser(user.accessKey)) as {
        memberOf?: string[]
        policyName?: string
        status?: string
      }
      setUser((prev) => ({
        ...prev,
        memberOf: latest?.memberOf ?? [],
        policy: latest?.policyName?.split(",").filter(Boolean) ?? [],
        status: latest?.status ?? "enabled",
      }))
    } catch {
      // ignore
    }
  }, [user.accessKey, getUser])

  React.useEffect(() => {
    if (open && row?.accessKey) {
      setUser({
        accessKey: row.accessKey,
        memberOf: (row.memberOf as string[]) ?? [],
        policy: Array.isArray(row.policy) ? row.policy : ((row.policyName as string)?.split(",").filter(Boolean) ?? []),
        status: (row.status as string) ?? "enabled",
      })
      setLoading(true)
      getUser(row.accessKey)
        .then((latest: { memberOf?: string[]; policyName?: string; status?: string }) => {
          setUser((prev) => ({
            ...prev,
            memberOf: latest?.memberOf ?? [],
            policy: latest?.policyName?.split(",").filter(Boolean) ?? [],
            status: latest?.status ?? "enabled",
          }))
        })
        .catch(() => {})
        .finally(() => setLoading(false))
    }
  }, [open, row, getUser])

  const handleStatusChange = async (checked: boolean) => {
    const nextStatus = checked ? "enabled" : "disabled"
    if (!user.accessKey) return
    try {
      await changeUserStatus(user.accessKey, { status: nextStatus })
      setUser((prev) => ({ ...prev, status: nextStatus }))
      await refreshUser()
      onSuccess()
    } catch {
      // revert on error
      setUser((prev) => ({ ...prev, status: prev.status }))
    }
  }

  const closeModal = () => onOpenChange(false)

  return (
    <Dialog open={open} onOpenChange={closeModal}>
      <DialogContent
        className="sm:max-w-lg"
        onPointerDownOutside={(e) => e.preventDefault()}
        onInteractOutside={(e) => e.preventDefault()}
      >
        <DialogHeader>
          <DialogTitle>{user.accessKey || row?.accessKey || t("Account")}</DialogTitle>
        </DialogHeader>

        <div className="space-y-4 max-h-[80vh] overflow-auto px-2 -mx-2">
          <div className="flex items-center justify-start gap-2 rounded-md border px-3 py-2">
            <span className="text-sm text-muted-foreground">{t("Status")}</span>
            <Switch checked={statusBoolean} onCheckedChange={handleStatusChange} disabled={loading} />
            <Button variant="outline" className="ml-auto" disabled>
              {t("Change Secret Key")} (Coming soon)
            </Button>
          </div>

          <p className="text-sm text-muted-foreground">
            {t("Groups")}: {user.memberOf?.join(", ") || "-"}
          </p>
          <p className="text-sm text-muted-foreground">
            {t("Policies")}: {user.policy?.join(", ") || "-"}
          </p>
        </div>
      </DialogContent>
    </Dialog>
  )
}
