// components/users/user/notice.vue
<template>
  <AppModal v-model="visible" :title="t('New user has been created')" size="md" :close-on-backdrop="false">
    <div class="space-y-4">
      <div class="space-y-2">
        <Label>{{ t('Access Key') }}</Label>
        <copy-input v-model="accessKey" class="w-full" :readonly="true" :copy-icon="true" />
      </div>
      <div class="space-y-2">
        <Label>{{ t('Secret Key') }}</Label>
        <copy-input v-model="secretkey" class="w-full" :readonly="true" :copy-icon="true" />
      </div>
    </div>

    <template #footer>
      <div class="flex justify-end gap-2">
        <Button variant="outline" @click="closeModal">{{ t('Cancel') }}</Button>
        <Button variant="default" @click="exportFile">{{ t('Export') }}</Button>
      </div>
    </template>
  </AppModal>
</template>

<script setup lang="ts">
import { Button } from '@/components/ui/button'

import { AppModal } from '@/components/app'
import { Label } from '@/components/ui/label'
import { download } from '@/utils/export-file'
import { ref } from 'vue'
import { useI18n } from 'vue-i18n'

const { t } = useI18n()
const visible = ref(false)

const accessKey = ref('')
const secretkey = ref('')
const url = ref('')

const emit = defineEmits<{
  (e: 'search'): void
}>()

const openDialog = (data: any) => {
  accessKey.value = data.credentials.accessKey
  secretkey.value = data.credentials.secretKey
  url.value = data.url
  visible.value = true
}

const closeModal = () => {
  visible.value = false
  accessKey.value = ''
  secretkey.value = ''
  emit('search')
}

const exportFile = () => {
  download(
    'credentials.json',
    JSON.stringify({
      url: url.value,
      accessKey: accessKey.value,
      secretKey: secretkey.value,
      api: 's3v4',
      path: 'auto',
    })
  )
}

defineExpose({
  openDialog,
})
</script>

// components/user/notice.tsx
"use client"

import * as React from "react"
import { useTranslation } from "react-i18next"
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { Button } from "@/components/ui/button"
import { Field, FieldContent, FieldLabel } from "@/components/ui/field"
import { CopyInput } from "@/components/copy-input"
import { download } from "@/lib/export-file"

export interface CredentialsData {
  credentials?: { accessKey?: string; secretKey?: string }
  url?: string
}

interface UserNoticeProps {
  open: boolean
  onOpenChange: (open: boolean) => void
  data?: CredentialsData | null
  onClose?: () => void
  title?: string
}

export function UserNotice({ open, onOpenChange, data, onClose, title }: UserNoticeProps) {
  const { t } = useTranslation()
  const accessKey = data?.credentials?.accessKey ?? ""
  const secretKey = data?.credentials?.secretKey ?? ""
  const url = data?.url ?? ""

  const closeModal = React.useCallback(() => {
    onOpenChange(false)
    onClose?.()
  }, [onOpenChange, onClose])

  const exportFile = React.useCallback(() => {
    download(
      "credentials.json",
      JSON.stringify({
        url,
        accessKey,
        secretKey,
        api: "s3v4",
        path: "auto",
      }),
    )
    closeModal()
  }, [url, accessKey, secretKey, closeModal])

  return (
    <Dialog open={open} onOpenChange={closeModal} disablePointerDismissal>
      <DialogContent className="sm:max-w-md">
        <DialogHeader>
          <DialogTitle>{title ?? t("New user has been created")}</DialogTitle>
        </DialogHeader>

        <div className="space-y-4">
          <Field>
            <FieldLabel>{t("Access Key")}</FieldLabel>
            <FieldContent>
              <CopyInput value={accessKey} readOnly copyIcon className="w-full" />
            </FieldContent>
          </Field>
          <Field>
            <FieldLabel>{t("Secret Key")}</FieldLabel>
            <FieldContent>
              <CopyInput value={secretKey} readOnly copyIcon className="w-full" />
            </FieldContent>
          </Field>
        </div>

        <DialogFooter>
          <Button variant="outline" onClick={closeModal}>
            {t("Cancel")}
          </Button>
          <Button variant="default" onClick={exportFile}>
            {t("Export")}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  )
}
