// pages/browser/index.vue
<template>
  <page>
    <page-header>
      <h1 class="text-2xl font-bold">{{ t('Buckets') }}</h1>
      <template #actions>
        <SearchInput v-model="searchTerm" :placeholder="t('Search')" clearable class="max-w-sm" />
        <Button variant="outline" @click="formVisible = true">
          <Icon name="ri:add-line" class="size-4" />
          <span>{{ t('Create Bucket') }}</span>
        </Button>
        <Button variant="outline" @click="() => refresh()">
          <Icon name="ri:refresh-line" class="size-4" />
          <span>{{ t('Refresh') }}</span>
        </Button>
      </template>
    </page-header>

    <DataTable
      :table="table"
      :is-loading="pending"
      :empty-title="t('No Buckets')"
      :empty-description="t('Create a bucket to start storing objects.')"
    />
  </page>

  <buckets-new-form :show="formVisible" @update:show="handleFormClosed" />
  <buckets-info ref="infoRef" />
</template>

<script lang="ts" setup>
import { Button } from '@/components/ui/button'

import { Icon, NuxtLink } from '#components'
import DataTable from '@/components/data-table/data-table.vue'
import { useDataTable } from '@/components/data-table/useDataTable'
import { niceBytes } from '@/utils/functions'
import type { ColumnDef } from '@tanstack/vue-table'
import dayjs from 'dayjs'
import { computed, h, ref } from 'vue'
import { useI18n } from 'vue-i18n'

const { t } = useI18n()
const message = useMessage()
const dialog = useDialog()
const { listBuckets, deleteBucket } = useBucket({})
const systemApi = useSystem()
const { isAdmin } = useAuth()

const formVisible = ref(false)
const searchTerm = ref('')

interface BucketRow {
  Name: string
  CreationDate: string
  Count?: number
  Size?: string
}

type BucketUsageMap = Record<string, { objects_count?: number; size?: number } | undefined>

const { data, pending, refresh } = await useAsyncData<BucketRow[]>(
  'buckets',
  async () => {
    const response = await listBuckets()

    // Only admin users can fetch data usage info
    let bucketUsage: BucketUsageMap = {}
    if (isAdmin.value) {
      const usage = await systemApi.getDataUsageInfo()
      bucketUsage = (usage?.buckets_usage ?? {}) as BucketUsageMap
    }

    const buckets = (response.Buckets ?? [])
      .map(item => {
        const name = item?.Name
        if (!name) {
          return null
        }

        const bucketRow: BucketRow = {
          Name: name,
          CreationDate: item?.CreationDate ? new Date(item.CreationDate).toISOString() : '',
        }

        // Only add Count and Size for admin users
        if (isAdmin.value) {
          const stats = bucketUsage[name]
          const objectsCount = typeof stats?.objects_count === 'number' ? stats.objects_count : 0
          const totalSize = typeof stats?.size === 'number' ? stats.size : 0
          bucketRow.Count = objectsCount
          bucketRow.Size = niceBytes(String(totalSize))
        }

        return bucketRow
      })
      .filter((bucket): bucket is BucketRow => bucket !== null)
      .sort((a, b) => a.Name.localeCompare(b.Name))

    return buckets
  },
  { default: () => [] as BucketRow[] }
)

const filteredData = computed(() => {
  const buckets = (data.value ?? []) as BucketRow[]
  if (!searchTerm.value) return buckets
  const term = searchTerm.value.toLowerCase()
  return buckets.filter(bucket => bucket.Name.toLowerCase().includes(term))
})

const columns = computed<ColumnDef<BucketRow>[]>(() => {
  const baseColumns: ColumnDef<BucketRow>[] = [
    {
      header: () => t('Bucket'),
      accessorKey: 'Name',
      cell: ({ row }) =>
        h(
          NuxtLink,
          {
            href: `/browser/${encodeURIComponent(row.original.Name)}`,
            class: 'flex items-center gap-2 text-primary hover:underline',
          },
          () => [h(Icon, { name: 'ri:archive-line', class: 'size-4' }), row.original.Name]
        ),
    },
    {
      header: () => t('Creation Date'),
      accessorKey: 'CreationDate',
      cell: ({ row }) => dayjs(row.original.CreationDate).format('YYYY-MM-DD HH:mm:ss'),
    },
  ]

  // Only admin users can see Count and Size columns
  if (isAdmin.value) {
    baseColumns.push(
      {
        header: () => t('Object Count'),
        accessorKey: 'Count',
        cell: ({ row }) => row.original.Count?.toLocaleString() ?? '0',
      },
      {
        header: () => t('Size'),
        accessorKey: 'Size',
      }
    )
  }

  baseColumns.push({
    id: 'actions',
    header: () => t('Actions'),
    enableSorting: false,
    meta: {
      width: 200,
    },
    cell: ({ row }) =>
      h('div', { class: 'flex items-center gap-2' }, [
        h(
          Button,
          {
            variant: 'outline',
            size: 'sm',
            onClick: () => openInfo(row.original.Name),
          },
          () => [h(Icon, { name: 'ri:settings-5-line', class: 'size-4' }), h('span', t('Settings'))]
        ),
        h(
          Button,
          {
            variant: 'outline',
            size: 'sm',
            onClick: () => confirmDelete(row.original),
          },
          () => [h(Icon, { name: 'ri:delete-bin-5-line', class: 'size-4' }), h('span', t('Delete'))]
        ),
      ]),
  })

  return baseColumns
})

const { table } = useDataTable<BucketRow>({
  data: filteredData,
  columns,
  manualPagination: true,
  getRowId: row => row.Name,
})

const infoRef = ref<{ openDrawer: (name: string) => void }>()

const handleFormClosed = (value: boolean) => {
  formVisible.value = value
  if (!value) refresh()
}

const openInfo = (name: string) => {
  infoRef.value?.openDrawer(name)
}

const confirmDelete = (row: BucketRow) => {
  dialog.error({
    title: t('Warning'),
    content: t('Are you sure you want to delete this bucket?'),
    positiveText: t('Confirm'),
    negativeText: t('Cancel'),
    onPositiveClick: () => deleteItem(row),
  })
}

const deleteItem = async (row: BucketRow) => {
  const objectApi = useObject({ bucket: row.Name })

  const files = await objectApi.listObject(row.Name, undefined, 1)
  const hasObjects =
    Boolean(files?.Contents?.some(item => Boolean(item?.Key))) || Boolean(files?.CommonPrefixes?.length)

  if (hasObjects) {
    message.error(t('Bucket is not empty'))
    return
  }

  try {
    await deleteBucket(row.Name)
    message.success(t('Delete Success'))
    await refresh()
  } catch (error: any) {
    message.error(error?.response?.data?.message || t('Delete Failed'))
  }
}
</script>

// app/(dashboard)/browser/page.tsx
"use client"

import { useState, useEffect, useCallback, useMemo, useRef } from "react"
import Link from "next/link"
import { useRouter, useSearchParams } from "next/navigation"
import { useTranslation } from "react-i18next"
import { RiAddLine, RiRefreshLine, RiArchiveLine, RiSettings5Line, RiDeleteBin5Line } from "@remixicon/react"
import { Button } from "@/components/ui/button"
import { SearchInput } from "@/components/search-input"
import { Page } from "@/components/page"
import { PageHeader } from "@/components/page-header"
import { DataTable } from "@/components/data-table/data-table"
import { useDataTable } from "@/hooks/use-data-table"
import { BucketNewForm } from "@/components/buckets/new-form"
import { Spinner } from "@/components/ui/spinner"
import { useBucket } from "@/hooks/use-bucket"
import { useObject } from "@/hooks/use-object"
import { useSystem } from "@/hooks/use-system"
import { useAuth } from "@/contexts/auth-context"
import { useDialog } from "@/lib/feedback/dialog"
import { useMessage } from "@/lib/feedback/message"
import { niceBytes } from "@/lib/functions"
import { BrowserContent } from "./content"
import type { ColumnDef } from "@tanstack/react-table"
import dayjs from "dayjs"

interface BucketRow {
  Name: string
  CreationDate: string
  Count?: number
  Size?: string
  SizeBytes?: number
}

type BucketUsageMap = Record<string, { objects_count?: number; size?: number } | undefined>

function BrowserBucketsPage() {
  const { t } = useTranslation()
  const router = useRouter()
  const message = useMessage()
  const dialog = useDialog()
  const { isAdmin } = useAuth()
  const { listBuckets, deleteBucket } = useBucket()
  const { getDataUsageInfo } = useSystem()

  const [formVisible, setFormVisible] = useState(false)
  const [searchTerm, setSearchTerm] = useState("")
  const [data, setData] = useState<BucketRow[]>([])
  const [pending, setPending] = useState(true)
  const [usageLoading, setUsageLoading] = useState(false)
  const fetchIdRef = useRef(0)

  const loadBucketUsage = useCallback(
    async (fetchId: number, bucketNames: string[]) => {
      if (bucketNames.length === 0) {
        setUsageLoading(false)
        return
      }

      try {
        const usage = (await getDataUsageInfo()) as { buckets_usage?: BucketUsageMap }
        if (fetchId !== fetchIdRef.current) return
        const bucketUsage = usage?.buckets_usage ?? {}

        setData((prev) =>
          prev.map((row) => {
            const stats = bucketUsage[row.Name]
            const objectsCount = typeof stats?.objects_count === "number" ? stats.objects_count : 0
            const totalSize = typeof stats?.size === "number" ? stats.size : 0
            return {
              ...row,
              Count: objectsCount,
              Size: niceBytes(String(totalSize)),
              SizeBytes: totalSize,
            }
          }),
        )
      } catch {
        if (fetchId !== fetchIdRef.current) return
      } finally {
        if (fetchId === fetchIdRef.current) {
          setUsageLoading(false)
        }
      }
    },
    [getDataUsageInfo],
  )

  const fetchBuckets = useCallback(
    async (options?: { force?: boolean }) => {
      const fetchId = fetchIdRef.current + 1
      fetchIdRef.current = fetchId
      setPending(true)
      try {
        const response = await listBuckets(options)
        if (fetchId !== fetchIdRef.current) return

        const buckets = ((response as { Buckets?: Array<{ Name?: string; CreationDate?: string }> })?.Buckets ?? [])
          .map((item) => {
            const name = item?.Name
            if (!name) return null

            const bucketRow: BucketRow = {
              Name: name,
              CreationDate: item?.CreationDate ? new Date(item.CreationDate).toISOString() : "",
            }

            return bucketRow
          })
          .filter((bucket): bucket is BucketRow => bucket !== null)
          .sort((a, b) => a.Name.localeCompare(b.Name))

        setData(buckets)
        setPending(false)

        setUsageLoading(true)
        void loadBucketUsage(
          fetchId,
          buckets.map((bucket) => bucket.Name),
        )
      } catch (error) {
        if (fetchId !== fetchIdRef.current) return
        console.error("Failed to fetch buckets:", error)
        setData([])
      } finally {
        if (fetchId === fetchIdRef.current) {
          setPending(false)
        }
      }
    },
    [listBuckets, loadBucketUsage],
  )

  useEffect(() => {
    fetchBuckets()
  }, [fetchBuckets])

  const filteredData = useMemo(
    () => (searchTerm ? data.filter((bucket) => bucket.Name.toLowerCase().includes(searchTerm.toLowerCase())) : data),
    [data, searchTerm],
  )

  const objectApi = useObject("")

  const baseColumns: ColumnDef<BucketRow>[] = [
    {
      header: () => t("Bucket"),
      accessorKey: "Name",
      cell: ({ row }) => (
        <Link
          href={`/browser?bucket=${encodeURIComponent(row.original.Name)}`}
          className="flex items-center gap-2 text-primary hover:underline"
        >
          <RiArchiveLine className="size-4" />
          {row.original.Name}
        </Link>
      ),
    },
    {
      header: () => t("Creation Date"),
      accessorKey: "CreationDate",
      cell: ({ row }) => dayjs(row.original.CreationDate).format("YYYY-MM-DD HH:mm:ss"),
    },
  ]

  baseColumns.push(
    {
      header: () => t("Object Count"),
      accessorKey: "Count",
      cell: ({ row }) =>
        typeof row.original.Count === "number" ? (
          row.original.Count.toLocaleString()
        ) : usageLoading ? (
          <Spinner className="size-3 text-muted-foreground" />
        ) : (
          "--"
        ),
    },
    {
      header: () => t("Size"),
      id: "SizeBytes",
      // use numeric bytes for sorting via accessorFn, but display the formatted string
      accessorFn: (row) => (typeof row.SizeBytes === "number" ? row.SizeBytes : undefined),
      cell: ({ row }) =>
        row.original.Size ?? (usageLoading ? <Spinner className="size-3 text-muted-foreground" /> : "--"),
    },
  )

  baseColumns.push({
    id: "actions",
    header: () => t("Actions"),
    enableSorting: false,
    meta: { width: 200 },
    cell: ({ row }) => (
      <div className="flex items-center gap-2">
        <Button
          variant="outline"
          size="sm"
          onClick={() => router.push(`/buckets?bucket=${encodeURIComponent(row.original.Name)}`)}
        >
          <RiSettings5Line className="size-4" />
          <span>{t("Settings")}</span>
        </Button>
        <Button variant="outline" size="sm" onClick={() => confirmDelete(row.original)}>
          <RiDeleteBin5Line className="size-4" />
          <span>{t("Delete")}</span>
        </Button>
      </div>
    ),
  })

  const { table } = useDataTable<BucketRow>({
    data: filteredData,
    columns: baseColumns,
    manualPagination: true,
    getRowId: (row) => row.Name,
  })

  const handleFormClosed = (value: boolean) => {
    setFormVisible(value)
    if (!value) fetchBuckets({ force: true })
  }

  const confirmDelete = (row: BucketRow) => {
    dialog.error({
      title: t("Warning"),
      content: t("Are you sure you want to delete this bucket?"),
      positiveText: t("Confirm"),
      negativeText: t("Cancel"),
      onPositiveClick: () => deleteItem(row),
    })
  }

  const deleteItem = async (row: BucketRow) => {
    const files = await objectApi.listObject(row.Name, undefined, 1)
    const hasObjects =
      Boolean((files as { Contents?: Array<{ Key?: string }> })?.Contents?.some((item) => Boolean(item?.Key))) ||
      Boolean((files as { CommonPrefixes?: unknown[] })?.CommonPrefixes?.length)

    if (hasObjects) {
      message.error(t("Bucket is not empty"))
      return
    }

    try {
      await deleteBucket(row.Name)
      message.success(t("Delete Success"))
      await fetchBuckets({ force: true })
    } catch (error: unknown) {
      message.error(
        (error as { response?: { data?: { message?: string } } })?.response?.data?.message || t("Delete Failed"),
      )
    }
  }

  return (
    <Page>
      <PageHeader
        actions={
          <>
            <SearchInput
              value={searchTerm}
              onChange={setSearchTerm}
              placeholder={t("Search")}
              clearable
              className="max-w-sm"
            />
            <Button variant="outline" onClick={() => setFormVisible(true)}>
              <RiAddLine className="size-4" />
              <span>{t("Create Bucket")}</span>
            </Button>
            <Button variant="outline" onClick={() => fetchBuckets({ force: true })}>
              <RiRefreshLine className="size-4" />
              <span>{t("Refresh")}</span>
            </Button>
          </>
        }
      >
        <h1 className="text-2xl font-bold">{t("Buckets")}</h1>
      </PageHeader>

      <DataTable
        table={table}
        isLoading={pending}
        emptyTitle={t("No Buckets")}
        emptyDescription={t("Create a bucket to start storing objects.")}
      />

      <BucketNewForm show={formVisible} onShowChange={handleFormClosed} />
    </Page>
  )
}

export default function BrowserPage() {
  const searchParams = useSearchParams()
  const bucketName = searchParams.get("bucket") ?? ""
  const keyPath = searchParams.get("key") ?? ""
  const preview = searchParams.get("preview") === "true"
  const previewKey = searchParams.get("previewKey") ?? ""

  if (bucketName) {
    return <BrowserContent bucketName={bucketName} keyPath={keyPath} preview={preview} previewKey={previewKey} />
  }

  return <BrowserBucketsPage />
}
