// components/object/info.vue
<template>
  <Drawer v-model="visible" :title="t('Object Details')" size="lg">
    <div class="space-y-4">
      <div class="flex flex-wrap items-center gap-2">
        <Button variant="outline" size="sm" @click="download">
          <Icon name="ri:download-line" class="size-4" />
          {{ t('Download') }}
        </Button>
        <Button variant="outline" size="sm" @click="openPreview">
          <Icon name="ri:eye-line" class="size-4" />
          {{ t('Preview') }}
        </Button>
        <Button variant="outline" size="sm" @click="() => (showTagView = true)">
          <Icon name="ri:price-tag-3-line" class="size-4" />
          {{ t('Set Tags') }}
        </Button>
        <Button variant="outline" size="sm" @click="viewVersions">
          <Icon name="ri:file-list-2-line" class="size-4" />
          {{ t('Versions') }}
        </Button>
        <Button v-if="lockStatus" variant="outline" size="sm" @click="() => (showRetentionView = true)">
          <Icon name="ri:lock-line" class="size-4" />
          {{ t('Retention') }}
        </Button>
      </div>

      <Item variant="outline" class="flex-col items-stretch gap-4">
        <ItemHeader class="items-center">
          <ItemTitle>{{ t('Info') }}</ItemTitle>
        </ItemHeader>
        <ItemContent class="space-y-3 text-sm w-full min-w-0">
          <TooltipProvider>
            <div class="flex items-center justify-between gap-3 min-w-0">
              <span class="font-medium text-muted-foreground">{{ t('Object Name') }}</span>
              <Tooltip>
                <TooltipTrigger as-child>
                  <span class="max-w-[60%] truncate">{{ object?.Key }}</span>
                </TooltipTrigger>
                <TooltipContent>
                  <p class="max-w-xs break-all">{{ object?.Key }}</p>
                </TooltipContent>
              </Tooltip>
            </div>
            <div class="flex items-center justify-between gap-3 min-w-0">
              <span class="font-medium text-muted-foreground">{{ t('Object Size') }}</span>
              <span>{{ object?.ContentLength }}</span>
            </div>
            <div class="flex items-center justify-between gap-3 min-w-0">
              <span class="font-medium text-muted-foreground">{{ t('Object Type') }}</span>
              <Tooltip>
                <TooltipTrigger as-child>
                  <span class="max-w-[60%] truncate">{{ object?.ContentType }}</span>
                </TooltipTrigger>
                <TooltipContent>
                  <p class="max-w-xs break-all">{{ object?.ContentType }}</p>
                </TooltipContent>
              </Tooltip>
            </div>
          </TooltipProvider>
          <div class="flex items-center justify-between gap-3 min-w-0">
            <span class="font-medium text-muted-foreground">ETag</span>
            <span>{{ object?.ETag }}</span>
          </div>
          <div class="flex items-center justify-between gap-3 min-w-0">
            <span class="font-medium text-muted-foreground">{{ t('Last Modified Time') }}</span>
            <span>{{ object?.LastModified }}</span>
          </div>
          <div class="flex items-center justify-between gap-3 min-w-0">
            <span class="font-medium text-muted-foreground">{{ t('Legal Hold') }}</span>
            <Switch :checked="lockStatus" @update:checked="toggleLegalHold" />
          </div>
          <div class="flex flex-col gap-2">
            <span class="font-medium text-muted-foreground">{{ t('Retention') + t('Policy') }}</span>
            <div class="flex flex-col gap-1">
              <span>{{ retention }}</span>
              <span v-if="retainUntilDate" class="text-xs text-muted-foreground">{{ retainUntilDate }}</span>
            </div>
          </div>
          <div class="line-divider border-t"></div>
          <div class="flex flex-col gap-3">
            <div class="flex items-center justify-between gap-3 min-w-0">
              <span class="font-medium text-muted-foreground">{{ t('Temporary URL Expiration') }}</span>
            </div>
            <div class="flex justify-between flex-wrap items-center gap-3">
              <div class="flex items-center gap-2">
                <Input
                  v-model.number="expirationDays"
                  type="number"
                  :min="0"
                  :max="7"
                  :placeholder="t('Days')"
                  class="w-20"
                  @input="validateAndUpdateExpiration"
                />
                <span class="text-sm text-muted-foreground">{{ t('Days') }}</span>
              </div>
              <div class="flex items-center gap-2">
                <Input
                  v-model.number="expirationHours"
                  type="number"
                  :min="0"
                  :max="expirationDays > 0 ? 23 : 24"
                  :placeholder="t('Hours')"
                  class="w-20"
                  @input="validateAndUpdateExpiration"
                />
                <span class="text-sm text-muted-foreground">{{ t('Hours') }}</span>
              </div>
              <div class="flex items-center gap-2">
                <Input
                  v-model.number="expirationMinutes"
                  type="number"
                  :min="0"
                  :max="59"
                  :placeholder="t('Minutes')"
                  class="w-20"
                  @input="validateAndUpdateExpiration"
                />
                <span class="text-sm text-muted-foreground">{{ t('Minutes') }}</span>
              </div>
            </div>
            <Button
              class="w-full sm:w-auto"
              variant="default"
              size="sm"
              :disabled="!object?.Key || !isExpirationValid"
              @click="generateTemporaryUrl"
            >
              {{ t('Generate URL') }}
            </Button>
            <div v-if="expirationError" class="text-xs text-destructive">{{ expirationError }}</div>
            <div v-if="totalExpirationSeconds > 0" class="text-xs text-muted-foreground">
              {{ t('Total Duration') }}: {{ formatDuration(totalExpirationSeconds) }}
            </div>
          </div>
          <div class="flex items-center gap-2">
            <copy-input v-model="signedUrl" class="w-full" :readonly="true" :copy-icon="true" />
          </div>
        </ItemContent>
      </Item>
    </div>

    <Modal v-model="showTagView" :title="t('Set Tags')" size="lg">
      <div class="space-y-4">
        <div class="flex flex-wrap gap-2">
          <Badge v-for="tag in tags" :key="tag.Key" variant="secondary"> {{ tag.Key }}: {{ tag.Value }} </Badge>
        </div>
        <form class="space-y-4" @submit.prevent="submitTagForm">
          <div class="grid gap-4 sm:grid-cols-2">
            <Field>
              <FieldLabel>{{ t('Tag Key') }}</FieldLabel>
              <FieldContent>
                <Input v-model="tagFormValue.Key" :placeholder="t('Tag Key Placeholder')" />
              </FieldContent>
            </Field>
            <Field>
              <FieldLabel>{{ t('Tag Value') }}</FieldLabel>
              <FieldContent>
                <Input v-model="tagFormValue.Value" :placeholder="t('Tag Value Placeholder')" />
              </FieldContent>
            </Field>
          </div>
          <div class="flex justify-end">
            <Button type="submit" variant="default">{{ t('Add') }}</Button>
          </div>
        </form>
      </div>
    </Modal>

    <Modal v-model="showRetentionView" :title="t('Retention')" size="lg">
      <div class="space-y-4">
        <form class="flex flex-col gap-3" @submit.prevent="submitRetention">
          <Field>
            <FieldLabel>{{ t('Retention Mode') }}</FieldLabel>
            <FieldContent>
              <RadioGroup v-model="retentionMode" class="grid gap-2 sm:grid-cols-2">
                <label
                  v-for="option in [
                    { label: t('COMPLIANCE'), value: 'COMPLIANCE' },
                    { label: t('GOVERNANCE'), value: 'GOVERNANCE' },
                  ]"
                  :key="option.value"
                  class="flex items-start gap-3 rounded-md border border-border/50 p-3"
                >
                  <RadioGroupItem :value="option.value" class="mt-0.5" />
                  <span class="text-sm font-medium">{{ option.label }}</span>
                </label>
              </RadioGroup>
            </FieldContent>
          </Field>
          <Field>
            <FieldLabel>{{ t('Retention RetainUntilDate') }}</FieldLabel>
            <FieldContent>
              <Input v-model="retainUntilDate" type="datetime-local" />
            </FieldContent>
          </Field>
          <div class="flex justify-end gap-2">
            <Button variant="secondary" @click="resetRetention">{{ t('Reset') }}</Button>
            <Button type="submit" variant="default">{{ t('Confirm') }}</Button>
            <Button variant="outline" @click="() => (showRetentionView = false)">{{ t('Cancel') }}</Button>
          </div>
        </form>
      </div>
    </Modal>

    <object-preview-modal v-model:show="showPreview" :object="previewObject ?? object" />
    <ObjectVersions
      :bucket-name="bucketName"
      :object-key="object?.Key || ''"
      :visible="showVersions"
      @close="handleVersionsClose"
      @preview="handlePreviewVersion"
      @refresh-parent="handleVersionsRefresh"
    />
  </Drawer>
</template>

<script setup lang="ts">
import { useNuxtApp } from '#app'
import { GetObjectCommand, HeadObjectCommand } from '@aws-sdk/client-s3'
import { getSignedUrl as presignGetObject } from '@aws-sdk/s3-request-presigner'
import { joinRelativeURL } from 'ufo'
import { ref, watch } from 'vue'
import { useI18n } from 'vue-i18n'

import ObjectVersions from '@/components/object/versions.vue'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Field, FieldContent, FieldLabel } from '@/components/ui/field'
import { Input } from '@/components/ui/input'
import { Item, ItemContent, ItemHeader, ItemTitle } from '@/components/ui/item'
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group'
import { Switch } from '@/components/ui/switch'
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from '@/components/ui/tooltip'
import Drawer from '~/components/drawer.vue'
import Modal from '~/components/modal.vue'

const { t } = useI18n()
const message = useMessage()
const { $s3Client } = useNuxtApp()

const props = defineProps<{
  bucketName: string
}>()

const visible = ref(false)
const object = ref<any>(null)
const tags = ref<Array<{ Key: string; Value: string }>>([])
const lockStatus = ref(false)
const retention = ref('')
const retainUntilDate = ref('')
const retentionMode = ref<'COMPLIANCE' | 'GOVERNANCE'>('GOVERNANCE')
const signedUrl = ref('')
const showTagView = ref(false)
const showRetentionView = ref(false)
const showPreview = ref(false)
const showVersions = ref(false)
const previewObject = ref<any | null>(null)

const tagFormValue = ref({ Key: '', Value: '' })

const {
  getObjectInfo,
  setLegalHold,
  putObjectTags,
  getObjectTags,
  getObjectRetention,
  putObjectRetention,
  getSignedUrl,
} = useObject({
  bucket: props.bucketName,
})

const openDrawer = async (_bucket: string, key: string) => {
  visible.value = true
  try {
    await loadObjectInfo(key)
    await fetchTags(key)
    await fetchRetention(key)
  } catch (error) {
    message.error(t('Failed to fetch object info'))
  }
}
// 有效期输入（天数、小时、分钟）
const expirationDays = ref<number>(0)
const expirationHours = ref<number>(0)
const expirationMinutes = ref<number>(0)
const expirationError = ref<string>('')
const totalExpirationSeconds = ref<number>(0)
const isExpirationValid = ref<boolean>(false)

// 一周的秒数
const ONE_WEEK_SECONDS = 7 * 24 * 60 * 60 // 604800

// 计算总时长（秒数）
const calculateTotalSeconds = (days: number, hours: number, minutes: number): number => {
  return days * 24 * 60 * 60 + hours * 60 * 60 + minutes * 60
}

// 验证有效期输入
const validateExpiration = (): boolean => {
  expirationError.value = ''

  // 处理空值和非数字值，转换为0
  const days = Number(expirationDays.value) || 0
  const hours = Number(expirationHours.value) || 0
  const minutes = Number(expirationMinutes.value) || 0

  // 检查是否为有效数字
  if (isNaN(days) || isNaN(hours) || isNaN(minutes)) {
    return false
  }

  // 检查分钟范围 (0-59)
  if (minutes < 0 || minutes > 59) {
    expirationError.value = t('Minutes must be between 0 and 59')
    return false
  }

  // 检查小时范围
  if (hours < 0) {
    expirationError.value = t('Hours must be between 0 and 23')
    return false
  }

  // 如果天数大于0，小时不能超过23
  if (days > 0 && hours > 23) {
    expirationError.value = t('Hours must be between 0 and 23')
    return false
  }

  // 如果天数为0，小时不能超过24
  if (days === 0 && hours > 24) {
    expirationError.value = t('Hours must be between 0 and 24 when days is 0')
    return false
  }

  // 检查天数范围 (0-7)
  if (days < 0 || days > 7) {
    expirationError.value = t('Days must be between 0 and 7')
    return false
  }

  // 如果小时为24，自动转换为1天0小时（在计算时处理）
  let finalDays = days
  let finalHours = hours
  if (hours === 24 && days === 0) {
    finalDays = 1
    finalHours = 0
  }

  // 计算总时长
  const totalSeconds = calculateTotalSeconds(finalDays, finalHours, minutes)

  // 检查总时长不能超过一周
  if (totalSeconds > ONE_WEEK_SECONDS) {
    expirationError.value = t('Total duration cannot exceed 7 days')
    return false
  }

  // 检查至少有一个值大于0
  if (totalSeconds === 0) {
    return false
  }

  totalExpirationSeconds.value = totalSeconds
  return true
}

// 验证并更新有效期
const validateAndUpdateExpiration = () => {
  isExpirationValid.value = validateExpiration()
}

// 格式化时长显示
const formatDuration = (seconds: number): string => {
  if (seconds === 0) return ''

  const days = Math.floor(seconds / (24 * 60 * 60))
  const hours = Math.floor((seconds % (24 * 60 * 60)) / (60 * 60))
  const minutes = Math.floor((seconds % (60 * 60)) / 60)

  const parts: string[] = []
  if (days > 0) parts.push(`${days} ${t('Days')}`)
  if (hours > 0) parts.push(`${hours} ${t('Hours')}`)
  if (minutes > 0) parts.push(`${minutes} ${t('Minutes')}`)

  return parts.join(' ')
}

// 生成临时链接
const generateTemporaryUrl = async () => {
  if (!object.value?.Key) return

  if (!validateExpiration()) {
    message.error(expirationError.value || t('Please enter a valid expiration time'))
    return
  }

  try {
    const url = await getSignedUrl(object.value.Key, totalExpirationSeconds.value)
    signedUrl.value = url
    message.success(t('URL generated successfully'))
  } catch (error: any) {
    message.error(error?.message || t('Failed to generate URL'))
  }
}

const loadObjectInfo = async (key: string) => {
  const info = await getObjectInfo(key)
  object.value = info
  lockStatus.value = info?.ObjectLockLegalHoldStatus === 'ON'
  // 默认不生成分享链接，重置有效期输入
  expirationDays.value = 0
  expirationHours.value = 0
  expirationMinutes.value = 0
  signedUrl.value = ''
  expirationError.value = ''
  totalExpirationSeconds.value = 0
  isExpirationValid.value = false
}

const fetchTags = async (key: string) => {
  try {
    const response = await getObjectTags(key)
    tags.value = response
  } catch (error) {
    tags.value = []
  }
}

const fetchRetention = async (key: string) => {
  try {
    const response = await getObjectRetention(key)
    retention.value = response.Mode ?? ''
    retainUntilDate.value = response.RetainUntilDate ?? ''
    retentionMode.value = response.Mode === 'COMPLIANCE' ? 'COMPLIANCE' : 'GOVERNANCE'
  } catch (error) {
    retention.value = ''
    retainUntilDate.value = ''
  }
}

const toggleLegalHold = async () => {
  if (!object.value) return
  try {
    await setLegalHold(object.value.Key, !lockStatus.value)
    lockStatus.value = !lockStatus.value
    message.success(t('Update Success'))
  } catch (error: any) {
    message.error(error?.message || t('Update Failed'))
  }
}

const submitTagForm = async () => {
  if (!object.value) return
  if (!tagFormValue.value.Key || !tagFormValue.value.Value) {
    message.error(t('Please fill in the correct format'))
    return
  }

  try {
    const nextTags = [...tags.value, { ...tagFormValue.value }]
    await putObjectTags(object.value.Key, nextTags)
    tags.value = nextTags
    tagFormValue.value = { Key: '', Value: '' }
    message.success(t('Create Success'))
  } catch (error: any) {
    message.error(error?.message || t('Create Failed'))
  }
}

const submitRetention = async () => {
  if (!object.value) return
  try {
    await putObjectRetention(object.value.Key, {
      Mode: retentionMode.value,
      RetainUntilDate: retainUntilDate.value || undefined,
    })
    message.success(t('Update Success'))
    showRetentionView.value = false
    fetchRetention(object.value.Key)
  } catch (error: any) {
    message.error(error?.message || t('Update Failed'))
  }
}

const resetRetention = async () => {
  if (!object.value) return
  try {
    await putObjectRetention(object.value.Key, { Mode: 'GOVERNANCE' })
    message.success(t('Update Success'))
    fetchRetention(object.value.Key)
  } catch (error: any) {
    message.error(error?.message || t('Update Failed'))
  }
}

const viewVersions = () => {
  if (!object.value) return
  showVersions.value = true
}

const openPreview = () => {
  const source = object.value
  if (!source) return
  previewObject.value = source
  showPreview.value = true
}

const handlePreviewVersion = async (versionId: string) => {
  if (!object.value?.Key) return
  try {
    const [head, signed] = await Promise.all([
      $s3Client.send(
        new HeadObjectCommand({
          Bucket: props.bucketName,
          Key: object.value.Key,
          VersionId: versionId == '00000000-0000-0000-0000-000000000000' ? undefined : versionId,
        })
      ),
      presignGetObject(
        $s3Client,
        new GetObjectCommand({
          Bucket: props.bucketName,
          Key: object.value.Key,
          VersionId: versionId == '00000000-0000-0000-0000-000000000000' ? undefined : versionId,
        }),
        { expiresIn: 3600 }
      ),
    ])
    previewObject.value = {
      ...head,
      Key: object.value.Key,
      SignedUrl: signed,
      VersionId: versionId == '00000000-0000-0000-0000-000000000000' ? undefined : versionId,
    }
    showPreview.value = true
  } catch (error: any) {
    message.error(error?.message || t('Failed to fetch versions'))
  }
}

const handleVersionsClose = () => {
  showVersions.value = false
}

const handleVersionsRefresh = async () => {
  if (!object.value?.Key) return
  try {
    await loadObjectInfo(object.value.Key)
  } catch (error: any) {
    message.error(error?.message || t('Failed to fetch object info'))
  }
}

watch(
  () => showPreview.value,
  value => {
    if (!value) previewObject.value = null
  }
)

const download = async () => {
  if (!object.value) return
  try {
    const url = await getSignedUrl(object.value.Key)
    fetch(url).then(async response => {
      const filename = object.value.Key.split('/').pop() || ''
      // 获取头信息，将 Headers 对象转换为普通对象
      // 如果服务器没有返回 content-type，根据文件扩展名推断
      const headers: any = {
        'content-type': getContentType(response.headers, filename),
        filename: response.headers.get('content-disposition')?.split('filename=')[1] || '',
      }
      let blob = await response.blob()
      exportFile({ headers, data: blob }, filename)
    })
  } catch (error: any) {
    message.error(error?.message || t('Download Failed'))
  }
}

defineExpose({
  openDrawer,
})
</script>

// components/object/info.tsx
"use client"

import * as React from "react"
import { useTranslation } from "react-i18next"
import { RiDownloadLine, RiEyeLine, RiPriceTag3Line, RiFileList2Line, RiLockLine, RiCloseLine } from "@remixicon/react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Badge } from "@/components/ui/badge"
import { Switch } from "@/components/ui/switch"
import { Spinner } from "@/components/ui/spinner"
import { Drawer, DrawerContent, DrawerHeader, DrawerTitle, DrawerDescription } from "@/components/ui/drawer"
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { Item, ItemContent, ItemHeader, ItemTitle } from "@/components/ui/item"
import { Field, FieldContent, FieldLabel } from "@/components/ui/field"
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group"
import { CopyInput } from "@/components/copy-input"
import { useObject } from "@/hooks/use-object"
import { useMessage } from "@/lib/feedback/message"
import { useDialog } from "@/lib/feedback/dialog"
import { exportFile } from "@/lib/export-file"
import { getContentType } from "@/lib/mime-types"
import { ObjectVersions } from "@/components/object/versions"
import { ObjectPreviewModal } from "@/components/object/preview-modal"
import { GetObjectCommand, HeadObjectCommand } from "@aws-sdk/client-s3"
import { getSignedUrl } from "@aws-sdk/s3-request-presigner"
import { useS3 } from "@/contexts/s3-context"

const ONE_WEEK_SECONDS = 7 * 24 * 60 * 60

interface ObjectInfoProps {
  bucketName: string
  objectKey: string | null
  open: boolean
  onOpenChange: (open: boolean) => void
  onRefresh?: () => void
  autoPreview?: boolean
  onPreviewChange?: (showPreview: boolean) => void
}

export function ObjectInfo({
  bucketName,
  objectKey,
  open,
  onOpenChange,
  autoPreview = false,
  onPreviewChange,
}: ObjectInfoProps) {
  const { t } = useTranslation()
  const message = useMessage()
  const dialog = useDialog()
  const objectApi = useObject(bucketName)
  const client = useS3()

  const [object, setObject] = React.useState<Record<string, unknown> | null>(null)
  const [tags, setTags] = React.useState<Array<{ Key: string; Value: string }>>([])
  const [lockStatus, setLockStatus] = React.useState(false)
  const [retention, setRetention] = React.useState("")
  const [retainUntilDate, setRetainUntilDate] = React.useState("")
  const [retentionMode, setRetentionMode] = React.useState<"COMPLIANCE" | "GOVERNANCE">("GOVERNANCE")
  const [signedUrl, setSignedUrl] = React.useState("")
  const [showTagView, setShowTagView] = React.useState(false)
  const [showRetentionView, setShowRetentionView] = React.useState(false)
  const [showPreview, setShowPreview] = React.useState(false)
  const [showVersions, setShowVersions] = React.useState(false)
  const [previewObject, setPreviewObject] = React.useState<Record<string, unknown> | null>(null)
  const [tagFormValue, setTagFormValue] = React.useState({
    Key: "",
    Value: "",
  })
  const [expirationDays, setExpirationDays] = React.useState(0)
  const [expirationHours, setExpirationHours] = React.useState(2)
  const [expirationMinutes, setExpirationMinutes] = React.useState(0)
  const [expirationError, setExpirationError] = React.useState("")
  const [totalExpirationSeconds, setTotalExpirationSeconds] = React.useState(0)
  const [isExpirationValid, setIsExpirationValid] = React.useState(false)
  const [isGeneratingUrl, setIsGeneratingUrl] = React.useState(false)

  const formatDuration = (seconds: number) => {
    if (seconds === 0) return ""
    const days = Math.floor(seconds / (24 * 60 * 60))
    const hours = Math.floor((seconds % (24 * 60 * 60)) / (60 * 60))
    const minutes = Math.floor((seconds % (60 * 60)) / 60)
    const parts: string[] = []
    if (days > 0) parts.push(`${days} ${t("Days")}`)
    if (hours > 0) parts.push(`${hours} ${t("Hours")}`)
    if (minutes > 0) parts.push(`${minutes} ${t("Minutes")}`)
    return parts.join(" ")
  }

  const validateExpiration = React.useCallback((): boolean => {
    setExpirationError("")
    const days = Number(expirationDays) || 0
    const hours = Number(expirationHours) || 0
    const minutes = Number(expirationMinutes) || 0

    if (isNaN(days) || isNaN(hours) || isNaN(minutes)) return false
    if (minutes < 0 || minutes > 59) {
      setExpirationError(t("Minutes must be between 0 and 59"))
      return false
    }
    if (hours < 0) {
      setExpirationError(t("Hours must be between 0 and 23"))
      return false
    }
    if (days > 0 && hours > 23) {
      setExpirationError(t("Hours must be between 0 and 23"))
      return false
    }
    if (days === 0 && hours > 24) {
      setExpirationError(t("Hours must be between 0 and 24 when days is 0"))
      return false
    }
    if (days < 0 || days > 7) {
      setExpirationError(t("Days must be between 0 and 7"))
      return false
    }

    let finalDays = days
    let finalHours = hours
    if (hours === 24 && days === 0) {
      finalDays = 1
      finalHours = 0
    }
    const totalSeconds = finalDays * 24 * 60 * 60 + finalHours * 60 * 60 + minutes * 60
    if (totalSeconds > ONE_WEEK_SECONDS) {
      setExpirationError(t("Total duration cannot exceed 7 days"))
      return false
    }
    if (totalSeconds === 0) {
      setTotalExpirationSeconds(0)
      return false
    }

    setTotalExpirationSeconds(totalSeconds)
    return true
  }, [expirationDays, expirationHours, expirationMinutes, t])

  React.useEffect(() => {
    setIsExpirationValid(validateExpiration())
  }, [expirationDays, expirationHours, expirationMinutes, validateExpiration])

  const loadObjectInfo = React.useCallback(
    async (key: string) => {
      const info = await objectApi.getObjectInfo(key)
      setObject(info as Record<string, unknown>)
      setLockStatus((info as { ObjectLockLegalHoldStatus?: string })?.ObjectLockLegalHoldStatus === "ON")
      setExpirationDays(0)
      setExpirationHours(2)
      setExpirationMinutes(0)
      setSignedUrl("")
      setExpirationError("")
      setTotalExpirationSeconds(2 * 60 * 60)
      setIsExpirationValid(true)
      setIsGeneratingUrl(false)
    },
    [objectApi],
  )

  const fetchTags = React.useCallback(
    async (key: string) => {
      try {
        const response = await objectApi.getObjectTags(key)
        setTags(response)
      } catch {
        setTags([])
      }
    },
    [objectApi],
  )

  const fetchRetention = React.useCallback(
    async (key: string) => {
      try {
        const response = await objectApi.getObjectRetention(key)
        setRetention(response.Mode ?? "")
        setRetainUntilDate(response.RetainUntilDate ?? "")
        setRetentionMode(response.Mode === "COMPLIANCE" ? "COMPLIANCE" : "GOVERNANCE")
      } catch {
        setRetention("")
        setRetainUntilDate("")
      }
    },
    [objectApi],
  )

  const loadObjectInfoRef = React.useRef(loadObjectInfo)
  const fetchTagsRef = React.useRef(fetchTags)
  const fetchRetentionRef = React.useRef(fetchRetention)

  React.useEffect(() => {
    loadObjectInfoRef.current = loadObjectInfo
    fetchTagsRef.current = fetchTags
    fetchRetentionRef.current = fetchRetention
  }, [loadObjectInfo, fetchTags, fetchRetention])

  React.useEffect(() => {
    if (open && objectKey) {
      const key = objectKey
      loadObjectInfoRef
        .current(key)
        .then(() => Promise.all([fetchTagsRef.current(key), fetchRetentionRef.current(key)]))
        .catch(() => {
          message.error(t("Failed to fetch object info"))
          setObject(null)
        })
    } else {
      setObject(null)
    }
  }, [open, objectKey, message, t])

  const download = async () => {
    if (!object?.Key) return
    try {
      const url = await objectApi.getSignedUrl(object.Key as string)
      const response = await fetch(url)
      const filename = (object.Key as string).split("/").pop() ?? ""
      const headers: Record<string, string> = {
        "content-type": getContentType(response.headers, filename),
        filename: response.headers.get("content-disposition")?.split("filename=")[1] ?? "",
      }
      const blob = await response.blob()
      exportFile({ headers, data: blob }, filename)
    } catch (err) {
      message.error((err as Error)?.message ?? t("Download Failed"))
    }
  }

  // Auto-open preview once when autoPreview is true and object data is first loaded
  const hasAutoPreviewedRef = React.useRef(false)
  React.useEffect(() => {
    if (!open) {
      hasAutoPreviewedRef.current = false
      return
    }
    if (autoPreview && object && !hasAutoPreviewedRef.current) {
      hasAutoPreviewedRef.current = true
      setShowPreview(true)
    }
  }, [autoPreview, object, open])

  // Open preview dialog
  const openPreview = () => {
    if (!object) return
    setPreviewObject(object)
    setShowPreview(true)
    onPreviewChange?.(true)
  }

  const handlePreviewVersion = async (versionId: string) => {
    if (!object?.Key) return
    try {
      const key = object.Key as string
      const version = versionId === "00000000-0000-0000-0000-000000000000" ? undefined : versionId
      const [head, signed] = await Promise.all([
        client.send(
          new HeadObjectCommand({
            Bucket: bucketName,
            Key: key,
            VersionId: version,
          }),
        ),
        getSignedUrl(
          client,
          new GetObjectCommand({
            Bucket: bucketName,
            Key: key,
            VersionId: version,
          }),
          { expiresIn: 3600 },
        ),
      ])
      setPreviewObject({
        ...head,
        Key: key,
        SignedUrl: signed,
        VersionId: version,
      })
      setShowPreview(true)
    } catch (err) {
      message.error((err as Error)?.message ?? t("Failed to fetch versions"))
    }
  }

  const toggleLegalHold = async () => {
    if (!object?.Key) return
    try {
      await objectApi.setLegalHold(object.Key as string, !lockStatus)
      setLockStatus(!lockStatus)
      message.success(t("Update Success"))
    } catch (err) {
      message.error((err as Error)?.message ?? t("Update Failed"))
    }
  }

  const generateTemporaryUrl = async () => {
    if (!object?.Key || isGeneratingUrl) return
    if (!validateExpiration()) {
      message.error(expirationError || t("Please enter a valid expiration time"))
      return
    }
    setIsGeneratingUrl(true)
    try {
      const url = await objectApi.getSignedUrl(object.Key as string, totalExpirationSeconds)
      setSignedUrl(url)
      message.success(t("URL generated successfully"))
    } catch (err) {
      message.error((err as Error)?.message ?? t("Failed to generate URL"))
    } finally {
      setIsGeneratingUrl(false)
    }
  }

  const submitTagForm = async (e: React.FormEvent) => {
    e.preventDefault()
    if (!object?.Key) return
    if (!tagFormValue.Key || !tagFormValue.Value) {
      message.error(t("Please fill in the correct format"))
      return
    }
    try {
      const nextTags = [...tags, { ...tagFormValue }]
      await objectApi.putObjectTags(object.Key as string, nextTags)
      setTags(nextTags)
      setTagFormValue({ Key: "", Value: "" })
      message.success(t("Create Success"))
    } catch (err) {
      message.error((err as Error)?.message ?? t("Create Failed"))
    }
  }

  const confirmDeleteTag = (tagKey: string) => {
    dialog.warning({
      title: t("Delete Tag"),
      content: t("Are you sure you want to delete this tag?"),
      positiveText: t("Confirm"),
      negativeText: t("Cancel"),
      onPositiveClick: () => removeTag(tagKey),
    })
  }

  const removeTag = async (tagKey: string) => {
    if (!object?.Key) return
    try {
      const nextTags = tags.filter((tag) => tag.Key !== tagKey)
      await objectApi.putObjectTags(object.Key as string, nextTags)
      setTags(nextTags)
      message.success(t("Delete Success"))
    } catch (err) {
      message.error((err as Error)?.message ?? t("Delete Failed"))
    }
  }

  const submitRetention = async (e: React.FormEvent) => {
    e.preventDefault()
    if (!object?.Key) return
    try {
      await objectApi.putObjectRetention(object.Key as string, {
        Mode: retentionMode,
        RetainUntilDate: retainUntilDate || undefined,
      })
      message.success(t("Update Success"))
      setShowRetentionView(false)
      fetchRetention(object.Key as string)
    } catch (err) {
      message.error((err as Error)?.message ?? t("Update Failed"))
    }
  }

  const resetRetention = async () => {
    if (!object?.Key) return
    try {
      await objectApi.putObjectRetention(object.Key as string, {
        Mode: "GOVERNANCE",
      })
      message.success(t("Update Success"))
      fetchRetention(object.Key as string)
    } catch (err) {
      message.error((err as Error)?.message ?? t("Update Failed"))
    }
  }

  const lastModified = object?.LastModified ? new Date(object.LastModified as string | Date).toISOString() : ""

  return (
    <>
      <Drawer open={open} onOpenChange={onOpenChange} direction="right">
        <DrawerContent className="max-h-[95vh] overflow-y-auto overflow-x-hidden data-[vaul-drawer-direction=right]:w-[92vw] data-[vaul-drawer-direction=right]:sm:max-w-2xl">
          <DrawerHeader>
            <DrawerTitle>{t("Object Details")}</DrawerTitle>
            <DrawerDescription />
          </DrawerHeader>
          <div className="min-w-0 space-y-4 p-4 overflow-hidden">
            <div className="flex flex-wrap items-center gap-2">
              <Button variant="outline" size="sm" onClick={download}>
                <RiDownloadLine className="size-4" />
                {t("Download")}
              </Button>
              <Button variant="outline" size="sm" onClick={openPreview}>
                <RiEyeLine className="size-4" />
                {t("Preview")}
              </Button>
              <Button variant="outline" size="sm" onClick={() => setShowTagView(true)}>
                <RiPriceTag3Line className="size-4" />
                {t("Set Tags")}
              </Button>
              <Button variant="outline" size="sm" onClick={() => setShowVersions(true)}>
                <RiFileList2Line className="size-4" />
                {t("Versions")}
              </Button>
              {lockStatus && (
                <Button variant="outline" size="sm" onClick={() => setShowRetentionView(true)}>
                  <RiLockLine className="size-4" />
                  {t("Retention")}
                </Button>
              )}
            </div>

            <Item variant="outline" className="flex-col items-stretch gap-4">
              <ItemHeader className="items-center">
                <ItemTitle>{t("Info")}</ItemTitle>
              </ItemHeader>
              <ItemContent className="min-w-0 space-y-3 text-sm overflow-hidden">
                <div className="flex items-center justify-between gap-3 min-w-0">
                  <span className="font-medium text-muted-foreground">{t("Object Name")}</span>
                  <span className="max-w-[60%] truncate text-right" title={String(object?.Key ?? "")}>
                    {String(object?.Key ?? "")}
                  </span>
                </div>
                <div className="flex items-center justify-between gap-3 min-w-0">
                  <span className="font-medium text-muted-foreground">{t("Object Size")}</span>
                  <span className="max-w-[60%] truncate text-right" title={String(object?.ContentLength ?? "-")}>
                    {String(object?.ContentLength ?? "-")}
                  </span>
                </div>
                <div className="flex items-center justify-between gap-3 min-w-0">
                  <span className="font-medium text-muted-foreground">{t("Object Type")}</span>
                  <span className="max-w-[60%] truncate text-right" title={String(object?.ContentType ?? "")}>
                    {String(object?.ContentType ?? "-")}
                  </span>
                </div>
                <div className="flex items-center justify-between gap-3 min-w-0">
                  <span className="font-medium text-muted-foreground">ETag</span>
                  <span className="max-w-[60%] truncate text-right" title={String(object?.ETag ?? "-")}>
                    {String(object?.ETag ?? "-")}
                  </span>
                </div>
                <div className="flex items-center justify-between gap-3 min-w-0">
                  <span className="font-medium text-muted-foreground">{t("Last Modified Time")}</span>
                  <span className="max-w-[60%] truncate text-right" title={lastModified || "-"}>
                    {lastModified || "-"}
                  </span>
                </div>
                <div className="flex items-center justify-between gap-3 min-w-0">
                  <span className="font-medium text-muted-foreground">{t("Legal Hold")}</span>
                  <Switch checked={lockStatus} onCheckedChange={toggleLegalHold} />
                </div>
                <div className="flex flex-col gap-2">
                  <span className="font-medium text-muted-foreground">
                    {t("Retention")}
                    {t("Policy")}
                  </span>
                  <div className="flex flex-col gap-1">
                    <span className="truncate" title={retention}>
                      {retention}
                    </span>
                    {retainUntilDate && (
                      <span className="text-xs text-muted-foreground truncate" title={retainUntilDate}>
                        {retainUntilDate}
                      </span>
                    )}
                  </div>
                </div>
                <div className="border-t pt-3 flex flex-col gap-3 min-w-0">
                  <span className="font-medium text-muted-foreground">{t("Temporary URL Expiration")}</span>
                  <div className="flex flex-wrap items-center gap-x-3 gap-y-2">
                    <div className="flex items-center gap-1.5 shrink-0">
                      <Input
                        type="number"
                        min={0}
                        max={7}
                        placeholder={t("Days")}
                        className="w-14 shrink-0"
                        value={expirationDays}
                        onChange={(e) => setExpirationDays(Number(e.target.value) || 0)}
                      />
                      <span className="text-sm text-muted-foreground whitespace-nowrap">{t("Days")}</span>
                    </div>
                    <div className="flex items-center gap-1.5 shrink-0">
                      <Input
                        type="number"
                        min={0}
                        max={expirationDays > 0 ? 23 : 24}
                        placeholder={t("Hours")}
                        className="w-14 shrink-0"
                        value={expirationHours}
                        onChange={(e) => setExpirationHours(Number(e.target.value) || 0)}
                      />
                      <span className="text-sm text-muted-foreground whitespace-nowrap">{t("Hours")}</span>
                    </div>
                    <div className="flex items-center gap-1.5 shrink-0">
                      <Input
                        type="number"
                        min={0}
                        max={59}
                        placeholder={t("Minutes")}
                        className="w-14 shrink-0"
                        value={expirationMinutes}
                        onChange={(e) => setExpirationMinutes(Number(e.target.value) || 0)}
                      />
                      <span className="text-sm text-muted-foreground whitespace-nowrap">{t("Minutes")}</span>
                    </div>
                    <Button
                      variant="default"
                      size="sm"
                      className="shrink-0"
                      disabled={!object?.Key || !isExpirationValid || isGeneratingUrl}
                      onClick={generateTemporaryUrl}
                    >
                      {isGeneratingUrl ? <Spinner className="size-4" /> : null}
                      <span>{t("Generate URL")}</span>
                    </Button>
                  </div>
                  {expirationError && <div className="text-xs text-destructive">{expirationError}</div>}
                  {totalExpirationSeconds > 0 && (
                    <div className="text-xs text-muted-foreground">
                      {t("Total Duration")}: {formatDuration(totalExpirationSeconds)}
                    </div>
                  )}
                </div>
                <div className="flex flex-col gap-2 min-w-0 w-full">
                  <CopyInput value={signedUrl} readonly copyIcon className="min-w-0 flex-1" />
                  {signedUrl && (
                    <div className="text-xs text-amber-600 mt-1">
                      {t("This link will expire when your session ends or at the specified time.")}
                    </div>
                  )}
                </div>
              </ItemContent>
            </Item>
          </div>
        </DrawerContent>
      </Drawer>

      <Dialog open={showTagView} onOpenChange={setShowTagView}>
        <DialogContent className="sm:max-w-lg">
          <DialogHeader>
            <DialogTitle>{t("Set Tags")}</DialogTitle>
          </DialogHeader>
          <div className="space-y-4">
            <div className="flex flex-wrap gap-2">
              {tags.map((tag) => (
                <Badge key={tag.Key} variant="secondary" className="gap-1 pr-1">
                  {tag.Key}: {tag.Value}
                  <button
                    type="button"
                    className="hover:text-destructive transition-colors"
                    onClick={() => confirmDeleteTag(tag.Key)}
                  >
                    <RiCloseLine className="size-3" />
                  </button>
                </Badge>
              ))}
            </div>
            <form className="space-y-4" onSubmit={submitTagForm}>
              <div className="grid gap-4 sm:grid-cols-2">
                <Field>
                  <FieldLabel>{t("Tag Key")}</FieldLabel>
                  <FieldContent>
                    <Input
                      value={tagFormValue.Key}
                      onChange={(e) => setTagFormValue((v) => ({ ...v, Key: e.target.value }))}
                      placeholder={t("Tag Key Placeholder")}
                    />
                  </FieldContent>
                </Field>
                <Field>
                  <FieldLabel>{t("Tag Value")}</FieldLabel>
                  <FieldContent>
                    <Input
                      value={tagFormValue.Value}
                      onChange={(e) =>
                        setTagFormValue((v) => ({
                          ...v,
                          Value: e.target.value,
                        }))
                      }
                      placeholder={t("Tag Value Placeholder")}
                    />
                  </FieldContent>
                </Field>
              </div>
              <div className="flex justify-end">
                <Button type="submit" variant="default">
                  {t("Add")}
                </Button>
              </div>
            </form>
          </div>
        </DialogContent>
      </Dialog>

      <Dialog open={showRetentionView} onOpenChange={setShowRetentionView}>
        <DialogContent className="sm:max-w-lg">
          <DialogHeader>
            <DialogTitle>{t("Retention")}</DialogTitle>
          </DialogHeader>
          <form className="flex flex-col gap-3" onSubmit={submitRetention}>
            <Field>
              <FieldLabel>{t("Retention Mode")}</FieldLabel>
              <FieldContent>
                <RadioGroup
                  value={retentionMode}
                  onValueChange={(v) => setRetentionMode(v as "COMPLIANCE" | "GOVERNANCE")}
                  className="grid gap-2 sm:grid-cols-2"
                >
                  {[
                    { label: t("COMPLIANCE"), value: "COMPLIANCE" },
                    { label: t("GOVERNANCE"), value: "GOVERNANCE" },
                  ].map((opt) => (
                    <label
                      key={opt.value}
                      className="flex items-start gap-3 rounded-md border border-border/50 p-3 cursor-pointer"
                    >
                      <RadioGroupItem value={opt.value} className="mt-0.5" />
                      <span className="text-sm font-medium">{opt.label}</span>
                    </label>
                  ))}
                </RadioGroup>
              </FieldContent>
            </Field>
            <Field>
              <FieldLabel>{t("Retention RetainUntilDate")}</FieldLabel>
              <FieldContent>
                <Input
                  type="datetime-local"
                  value={retainUntilDate}
                  onChange={(e) => setRetainUntilDate(e.target.value)}
                />
              </FieldContent>
            </Field>
            <div className="flex justify-end gap-2">
              <Button type="button" variant="secondary" onClick={resetRetention}>
                {t("Reset")}
              </Button>
              <Button type="submit" variant="default">
                {t("Confirm")}
              </Button>
              <Button type="button" variant="outline" onClick={() => setShowRetentionView(false)}>
                {t("Cancel")}
              </Button>
            </div>
          </form>
        </DialogContent>
      </Dialog>

      <ObjectPreviewModal
        show={showPreview}
        onShowChange={(show) => {
          setShowPreview(show)
          onPreviewChange?.(show)
        }}
        object={previewObject ?? object}
      />
      <ObjectVersions
        bucketName={bucketName}
        objectKey={(object?.Key as string) ?? ""}
        visible={showVersions}
        onClose={() => setShowVersions(false)}
        onPreview={handlePreviewVersion}
        onRefreshParent={() => objectKey && loadObjectInfo(objectKey)}
      />
    </>
  )
}
