// components/object/list.tsx
"use client"

import * as React from "react"
import Link from "next/link"
import { useTranslation } from "react-i18next"
import {
  RiFileAddLine,
  RiDeleteBin5Line,
  RiDownloadCloud2Line,
  RiRefreshLine,
  RiFolderLine,
  RiFileLine,
  RiArrowLeftSLine,
  RiArrowRightSLine,
  RiEyeLine,
} from "@remixicon/react"
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "@/components/ui/alert-dialog"
import { Button } from "@/components/ui/button"
import { Checkbox } from "@/components/ui/checkbox"
import { SearchInput } from "@/components/search-input"
import { PageHeader } from "@/components/page-header"
import { DataTable } from "@/components/data-table/data-table"
import { useDataTable } from "@/hooks/use-data-table"
import { useObject } from "@/hooks/use-object"
import { useBucket } from "@/hooks/use-bucket"
import { useLocalStorage } from "@/hooks/use-local-storage"
import { useMessage } from "@/lib/feedback/message"
import { exportFile } from "@/lib/export-file"
import { getContentType } from "@/lib/mime-types"
import { formatBytes } from "@/lib/functions"
import { buildBucketPath } from "@/lib/bucket-path"
import { TaskStatsButton } from "@/components/tasks/stats-button"
import { useAddDeleteKeys } from "@/contexts/task-context"
import type { ColumnDef } from "@tanstack/react-table"
import dayjs from "dayjs"
import { saveAs } from "file-saver"
import JSZip from "jszip"

interface ObjectRow {
  Key: string
  type: "prefix" | "object"
  Size: number
  LastModified: string
}

interface ObjectListProps {
  bucket: string
  path: string
  onOpenInfo: (bucket: string, key: string) => void
  onUploadClick: () => void
  pageSize?: number
  onRefresh?: () => void
  refreshTrigger?: number
}

export function ObjectList({
  bucket,
  path,
  onOpenInfo,
  onUploadClick,
  pageSize = 25,
  onRefresh,
  refreshTrigger = 0,
}: ObjectListProps) {
  const { t } = useTranslation()
  const message = useMessage()
  const { listObject, getSignedUrl, mapAllFiles } = useObject(bucket)
  const { getBucketVersioning } = useBucket()
  const addDeleteKeys = useAddDeleteKeys()

  const [searchTerm, setSearchTerm] = React.useState("")
  const [showDeleted, setShowDeleted] = useLocalStorage("object-list-show-deleted", false)
  const [loading, setLoading] = React.useState(false)
  const [data, setData] = React.useState<ObjectRow[]>([])
  const [continuationToken, setContinuationToken] = React.useState<string | undefined>()
  const [tokenHistory, setTokenHistory] = React.useState<string[]>([])
  const [nextToken, setNextToken] = React.useState<string | undefined>()
  const [bucketVersioningEnabled, setBucketVersioningEnabled] = React.useState(false)
  const [deleteDialogOpen, setDeleteDialogOpen] = React.useState(false)
  const [deleteDialogKeys, setDeleteDialogKeys] = React.useState<string[]>([])
  const [deleteAllVersions, setDeleteAllVersions] = React.useState(false)

  const prefix = decodeURIComponent(path)

  const bucketPath = React.useCallback((p?: string | string[]) => buildBucketPath(bucket, p), [bucket])

  const fetchObjects = React.useCallback(
    async (tokenOverride?: string) => {
      const token = tokenOverride !== undefined ? tokenOverride : continuationToken
      setLoading(true)
      try {
        const response = await listObject(bucket, prefix || undefined, pageSize, token, {
          includeDeleted: showDeleted,
        })

        const r = response as {
          CommonPrefixes?: Array<{ Prefix?: string }>
          Contents?: Array<{ Key?: string; Size?: number; LastModified?: Date }>
          NextContinuationToken?: string
        }

        setNextToken(r.NextContinuationToken)

        const prefixItems: ObjectRow[] = (r.CommonPrefixes ?? []).map((item) => ({
          Key: item.Prefix ?? "",
          type: "prefix" as const,
          Size: 0,
          LastModified: "",
        }))

        const objectItems: ObjectRow[] = (r.Contents ?? []).map((item) => ({
          Key: item.Key ?? "",
          type: "object" as const,
          Size: item.Size ?? 0,
          LastModified: item.LastModified ? item.LastModified.toISOString() : "",
        }))

        setData([...prefixItems, ...objectItems])
      } finally {
        setTimeout(() => setLoading(false), 200)
      }
    },
    [bucket, prefix, pageSize, continuationToken, showDeleted, listObject],
  )

  const prevRefreshTriggerRef = React.useRef(refreshTrigger)

  React.useEffect(() => {
    const isRefresh = prevRefreshTriggerRef.current !== refreshTrigger
    prevRefreshTriggerRef.current = refreshTrigger

    if (isRefresh) {
      setContinuationToken(undefined)
      setTokenHistory([])
      void fetchObjects(undefined)
    } else {
      void fetchObjects()
    }
  }, [bucket, prefix, pageSize, continuationToken, showDeleted, refreshTrigger, fetchObjects])

  React.useEffect(() => {
    const loadBucketVersioningStatus = async () => {
      try {
        const resp = await getBucketVersioning(bucket)
        setBucketVersioningEnabled((resp as { Status?: string })?.Status === "Enabled")
      } catch {
        setBucketVersioningEnabled(false)
      }
    }
    loadBucketVersioningStatus()
  }, [bucket, getBucketVersioning])

  React.useEffect(() => {
    setContinuationToken(undefined)
    setTokenHistory([])
  }, [showDeleted])

  const displayKey = React.useCallback(
    (key: string) => {
      if (!prefix) return key
      return key.startsWith(prefix) ? key.slice(prefix.length) : key
    },
    [prefix],
  )

  const filteredData = React.useMemo(() => {
    const term = searchTerm.toLowerCase()
    return data.filter((item) => {
      if (term) {
        const key = displayKey(item.Key).toLowerCase()
        return key.includes(term)
      }
      return item.Key !== prefix
    })
  }, [data, searchTerm, prefix, displayKey])

  const downloadFile = React.useCallback(
    async (key: string) => {
      if (!key) return
      const loadingMsg = message.loading(t("Getting URL"), { duration: 0 })
      try {
        const url = await getSignedUrl(key)
        const response = await fetch(url)
        const filename = key.split("/").pop() ?? ""
        const headers: Record<string, string> = {
          "content-type": getContentType(response.headers, filename),
          filename: response.headers.get("content-disposition")?.split("filename=")[1] ?? "",
        }
        const blob = await response.blob()
        exportFile({ headers, data: blob }, filename)
      } catch (err) {
        message.error((err as Error)?.message ?? t("Download Failed"))
      } finally {
        loadingMsg.destroy()
      }
    },
    [message, t, getSignedUrl],
  )

  const columns: ColumnDef<ObjectRow>[] = React.useMemo(
    () => [
      {
        id: "object",
        header: () => t("Object"),
        accessorFn: (row) => displayKey(row.Key ?? ""),
        cell: ({ row }) => {
          const key = row.original.Key ?? ""
          const display = displayKey(key) || "/"

          if (row.original.type === "prefix") {
            return (
              <Link
                href={bucketPath(row.original.Key)}
                className="flex items-center gap-2 text-blue-500 hover:underline"
              >
                <RiFolderLine className="size-4" />
                <span>{display}</span>
              </Link>
            )
          }
          return (
            <button
              type="button"
              className="flex items-center gap-2 text-primary hover:underline text-left"
              onClick={() => onOpenInfo(bucket, row.original.Key)}
            >
              <RiFileLine className="size-4" />
              <span>{display}</span>
            </button>
          )
        },
        filterFn: (row, _columnId, filterValue) => {
          if (!filterValue) return true
          const key = displayKey(row.original.Key ?? "").toLowerCase()
          return key.includes(String(filterValue).toLowerCase())
        },
      },
      {
        id: "size",
        header: () => t("Size"),
        accessorFn: (row) => (row.type === "object" ? row.Size : -1),
        cell: ({ row }) => (row.original.type === "object" ? formatBytes(row.original.Size) : "-"),
      },
      {
        id: "lastModified",
        header: () => t("Last Modified"),
        accessorFn: (row) => (row.type === "prefix" || !row.LastModified ? "" : new Date(row.LastModified).getTime()),
        cell: ({ row }) =>
          row.original.LastModified ? dayjs(row.original.LastModified).format("YYYY-MM-DD HH:mm:ss") : "-",
      },
      {
        id: "actions",
        header: () => t("Actions"),
        enableSorting: false,
        cell: ({ row }) => (
          <div className="flex items-center gap-2">
            {row.original.type === "object" ? (
              <>
                <Button variant="outline" size="sm" asChild>
                  <Link
                    href={`/browser?bucket=${encodeURIComponent(bucket)}&key=${encodeURIComponent(prefix)}&preview=true&previewKey=${encodeURIComponent(row.original.Key)}`}
                  >
                    <RiEyeLine className="size-4" />
                    <span>{t("Preview")}</span>
                  </Link>
                </Button>
                <Button variant="outline" size="sm" onClick={() => downloadFile(row.original.Key)}>
                  <RiDownloadCloud2Line className="size-4" />
                  <span>{t("Download")}</span>
                </Button>
              </>
            ) : null}
            <Button variant="outline" size="sm" onClick={() => openDeleteDialog([row.original.Key])}>
              <RiDeleteBin5Line className="size-4" />
              <span>{t("Delete")}</span>
            </Button>
          </div>
        ),
      },
    ],
    [t, displayKey, bucketPath, onOpenInfo, bucket, prefix, downloadFile],
  )

  const { table, selectedRowIds } = useDataTable<ObjectRow>({
    data: filteredData,
    columns,
    getRowId: (row) => row.Key,
    enableRowSelection: true,
    manualPagination: true,
  })

  const checkedKeys = selectedRowIds

  const computeRelativeKey = (key: string) => {
    if (!key) return ""
    const base = prefix || ""
    return base && key.startsWith(base) ? key.slice(base.length) : key
  }

  const collectKeysForDeletion = async (keys: string[], forceDelete = false): Promise<string[]> => {
    const rowMap = new Map(data.map((item) => [item.Key, item]))
    const collected: string[] = []

    for (const key of keys) {
      if (!key) continue
      const row = rowMap.get(key)
      if (row?.type === "prefix") {
        collected.push(row.Key)
        if (!forceDelete) {
          await mapAllFiles(bucket, row.Key, (fileKey) => {
            if (fileKey) collected.push(fileKey)
          })
        }
      } else {
        collected.push(key)
      }
    }

    return Array.from(new Set(collected))
  }

  const downloadMultiple = async () => {
    if (!checkedKeys.length) {
      message.warning(t("Please select at least one item"))
      return
    }

    const selectedRows = data.filter((item) => checkedKeys.includes(item.Key))
    if (!selectedRows.length) {
      message.warning(t("No files to download"))
      return
    }

    const collecting = message.loading(t("Collecting files"), { duration: 0 })
    const allFiles: { key: string; relative: string }[] = []

    try {
      for (const item of selectedRows) {
        if (item.type === "object") {
          allFiles.push({
            key: item.Key,
            relative: computeRelativeKey(item.Key),
          })
        } else if (item.type === "prefix") {
          await mapAllFiles(bucket, item.Key, (fileKey) => {
            allFiles.push({
              key: fileKey,
              relative: computeRelativeKey(fileKey),
            })
          })
        }
      }
    } catch (err) {
      collecting.destroy()
      message.error((err as Error)?.message ?? t("Download Failed"))
      return
    }

    collecting.destroy()

    if (!allFiles.length) {
      message.warning(t("No files to download"))
      return
    }

    const zip = new JSZip()
    let finished = 0
    const destroyRef: { current: (() => void) | null } = { current: null }

    const updateProgress = () => {
      if (destroyRef.current) destroyRef.current()
      const handle = message.loading(`${t("Downloading files")} ${Math.round((finished / allFiles.length) * 100)}%`, {
        duration: 0,
      })
      destroyRef.current = handle.destroy
    }

    updateProgress()

    try {
      await Promise.all(
        allFiles.map(async ({ key, relative }) => {
          const url = await getSignedUrl(key)
          const response = await fetch(url)
          const blob = await response.blob()
          zip.file(relative || key, blob)
          finished++
          updateProgress()
        }),
      )
    } catch (err) {
      if (destroyRef.current) destroyRef.current()
      message.error((err as Error)?.message ?? t("Download Failed"))
      return
    }

    if (destroyRef.current) destroyRef.current()

    const content = await zip.generateAsync({ type: "blob" })
    saveAs(content, `${bucket ?? "download"}.zip`)
    message.success(t("Download ready"))
  }

  const openDeleteDialog = (keys: string[]) => {
    setDeleteDialogKeys(keys)
    setDeleteAllVersions(false)
    setDeleteDialogOpen(true)
  }

  const handleConfirmDelete = async () => {
    const keys = [...deleteDialogKeys]
    setDeleteDialogOpen(false)
    if (!keys.length) return

    if ((bucketVersioningEnabled && deleteAllVersions) || !bucketVersioningEnabled) {
      await handleDeleteAllVersions(keys)
    } else {
      await handleDelete(keys)
    }
  }

  const handleDelete = async (keys: string[]) => {
    try {
      const targets = await collectKeysForDeletion(keys)
      if (!targets.length) {
        message.success(t("Delete Success"))
      } else {
        addDeleteKeys(targets, bucket, undefined)
        message.success(t("Delete task created"))
      }
      table.resetRowSelection()
      ;(onRefresh ?? fetchObjects)()
    } catch (err) {
      message.error((err as Error)?.message ?? t("Delete Failed"))
    }
  }

  const handleDeleteAllVersions = async (keys: string[]) => {
    try {
      const targets = await collectKeysForDeletion(keys, true)
      if (!targets.length) {
        message.success(t("Delete Success"))
      } else {
        addDeleteKeys(targets, bucket, undefined, { forceDelete: true })
        message.success(t("Delete task created"))
      }
      table.resetRowSelection()
      ;(onRefresh ?? fetchObjects)()
    } catch (err) {
      message.error((err as Error)?.message ?? t("Delete Failed"))
    }
  }

  const handleBatchDelete = () => {
    if (!checkedKeys.length) {
      message.warning(t("Please select at least one item"))
      return
    }
    openDeleteDialog([...checkedKeys])
  }

  const goToNextPage = () => {
    if (!nextToken) return
    if (continuationToken) {
      setTokenHistory((h) => [...h, continuationToken])
    }
    setContinuationToken(nextToken)
  }

  const goToPreviousPage = () => {
    const prev = tokenHistory[tokenHistory.length - 1]
    if (prev !== undefined) {
      setTokenHistory((h) => h.slice(0, -1))
      setContinuationToken(prev)
    } else {
      setContinuationToken(undefined)
    }
  }

  React.useEffect(() => {
    const col = table.getColumn("object")
    if (col) col.setFilterValue(searchTerm || undefined)
  }, [searchTerm, table])

  return (
    <div className="space-y-6">
      <PageHeader
        actions={
          <>
            <TaskStatsButton />
            <Button variant="outline" onClick={onUploadClick}>
              <RiFileAddLine className="size-4" />
              <span>
                {t("Upload File")}/{t("Folder")}
              </span>
            </Button>
            {checkedKeys.length > 0 ? (
              <>
                <Button variant="outline" className="text-destructive border-destructive" onClick={handleBatchDelete}>
                  <RiDeleteBin5Line className="size-4" />
                  <span>{t("Delete Selected")}</span>
                </Button>
                <Button variant="outline" onClick={downloadMultiple}>
                  <RiDownloadCloud2Line className="size-4" />
                  <span>{t("Download")}</span>
                </Button>
              </>
            ) : null}
            <Button variant="outline" onClick={() => (onRefresh ?? fetchObjects)()}>
              <RiRefreshLine className="size-4" />
              <span>{t("Refresh")}</span>
            </Button>
          </>
        }
      >
        <div className="flex flex-wrap items-center gap-4 min-w-[40vw]">
          <SearchInput
            value={searchTerm}
            onChange={setSearchTerm}
            placeholder={t("Filter From This Page")}
            clearable
            className="lg:max-w-sm"
          />
          <label className="flex items-center gap-2 text-sm text-muted-foreground cursor-pointer">
            <Checkbox checked={showDeleted} onCheckedChange={(v) => setShowDeleted(v === true)} />
            <span>{t("Show Deleted Objects")}</span>
          </label>
        </div>
      </PageHeader>

      <DataTable
        table={table}
        isLoading={loading}
        emptyTitle={t("No Objects")}
        emptyDescription={t("Upload files or create folders to populate this bucket.")}
      />

      <div className="flex justify-end gap-2">
        <Button variant="outline" disabled={tokenHistory.length === 0} onClick={goToPreviousPage}>
          <RiArrowLeftSLine className="mr-2 size-4" />
          <span>{t("Previous Page")}</span>
        </Button>
        <Button variant="outline" disabled={!nextToken} onClick={goToNextPage}>
          <span>{t("Next Page")}</span>
          <RiArrowRightSLine className="ml-2 size-4" />
        </Button>
      </div>

      <AlertDialog open={deleteDialogOpen} onOpenChange={setDeleteDialogOpen}>
        <AlertDialogContent className="sm:max-w-md">
          <AlertDialogHeader>
            <AlertDialogTitle>{t("Warning")}</AlertDialogTitle>
            <AlertDialogDescription>
              {t("Are you sure you want to delete the selected objects?")}
              {bucketVersioningEnabled && (
                <label className="mt-4 flex items-center gap-2">
                  <Checkbox checked={deleteAllVersions} onCheckedChange={(v) => setDeleteAllVersions(v === true)} />
                  <span>{t("Delete All Versions")}</span>
                </label>
              )}
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel asChild>
              <Button variant="outline" className="w-full sm:w-auto text-foreground">
                {t("Cancel")}
              </Button>
            </AlertDialogCancel>
            <AlertDialogAction asChild>
              <Button variant="destructive" className="w-full sm:w-auto text-white" onClick={handleConfirmDelete}>
                {t("Confirm")}
              </Button>
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </div>
  )
}

// components/object/list.vue
<template>
  <div class="space-y-6">
    <page-header>
      <div class="flex flex-wrap items-center gap-4 min-w-[40vw]">
        <FilterInput v-model="searchTerm" :placeholder="t('Filter From This Page')" clearable class="lg:max-w-sm" />
        <label class="flex items-center gap-2 text-sm text-muted-foreground">
          <Checkbox v-model="showDeleted" />
          <span>{{ t('Show Deleted Objects') }}</span>
        </label>
      </div>
      <template #actions>
        <object-task-stats :tasks="taskStore.tasks" :on-clear-tasks="taskStore.clearTasks">
          <template #task-list="{ tasks }">
            <object-task-list :tasks="tasks" />
          </template>
        </object-task-stats>
        <!-- <Button variant="outline" @click="() => handleNewObject(true)">
          <Icon name="ri:add-line" class="size-4" />
          <span>{{ t('New Folder') }}</span>
        </Button> -->
        <Button variant="outline" @click="() => (uploadPickerVisible = true)">
          <Icon name="ri:file-add-line" class="size-4" />
          <span>{{ t('Upload File') }}/{{ t('Folder') }}</span>
        </Button>
        <Button
          variant="outline"
          class="text-destructive border-destructive"
          :disabled="!checkedKeys.length"
          v-show="checkedKeys.length"
          @click="handleBatchDelete"
        >
          <Icon name="ri:delete-bin-5-line" class="size-4" />
          <span>{{ t('Delete Selected') }}</span>
        </Button>
        <Button variant="outline" :disabled="!checkedKeys.length" v-show="checkedKeys.length" @click="downloadMultiple">
          <Icon name="ri:download-cloud-2-line" class="size-4" />
          <span>{{ t('Download') }}</span>
        </Button>
        <Button variant="outline" @click="handleRefresh">
          <Icon name="ri:refresh-line" class="size-4" />
          <span>{{ t('Refresh') }}</span>
        </Button>
      </template>
    </page-header>

    <DataTable
      :table="table"
      :is-loading="loading"
      :empty-title="t('No Objects')"
      :empty-description="t('Upload files or create folders to populate this bucket.')"
    />
    <div class="flex justify-end gap-2">
      <Button variant="outline" :disabled="!continuationToken" @click="goToPreviousPage">
        <Icon name="ri:arrow-left-s-line" class="mr-2" />
        <span>{{ t('Previous Page') }}</span>
      </Button>
      <Button variant="outline" :disabled="!nextToken" @click="goToNextPage">
        <span>{{ t('Next Page') }}</span>
        <Icon name="ri:arrow-right-s-line" class="ml-2" />
      </Button>
    </div>
  </div>

  <object-upload-picker
    :show="uploadPickerVisible"
    :bucketName="bucketName"
    :prefix="prefix"
    @update:show="
      val => {
        uploadPickerVisible = val
        refresh()
      }
    "
  />
  <object-new-form
    :show="newObjectFormVisible"
    :bucketName="bucketName"
    :prefix="prefix"
    :asPrefix="newObjectAsPrefix"
    @update:show="
      val => {
        newObjectFormVisible = val
        refresh()
      }
    "
  />
  <object-info ref="infoRef" :bucket-name="bucketName" @refresh-parent="handleObjectDeleted" />
</template>

<script setup lang="ts">
import { Button } from '@/components/ui/button'
import { Checkbox } from '@/components/ui/checkbox'

import { useLocalStorage } from '@vueuse/core'

import { Icon, NuxtLink } from '#components'
import DataTable from '@/components/data-table/data-table.vue'
import { useDataTable } from '@/components/data-table/useDataTable'
import { ListObjectsV2Command } from '@aws-sdk/client-s3'
import type { HttpRequest } from '@smithy/protocol-http'
import type { ColumnDef } from '@tanstack/vue-table'
import dayjs from 'dayjs'
import { saveAs } from 'file-saver'
import JSZip from 'jszip'
import { joinRelativeURL } from 'ufo'
import type { VNode } from 'vue'
import { computed, h, onMounted, onUnmounted, ref, watch } from 'vue'
import { useTaskManagerStore } from '~/store/tasks'

const { $s3Client } = useNuxtApp()
const { t } = useI18n()
const route = useRoute()
const dialog = useDialog()
const props = defineProps<{ bucket: string; path: string }>()

const uploadPickerVisible = ref(false)
const newObjectFormVisible = ref(false)
const newObjectAsPrefix = ref(false)
const searchTerm = ref('')
const loading = ref(false)
const showDeleted = useLocalStorage('object-list-show-deleted', false)

const debounce = (fn: Function, delay: number) => {
  let timer: NodeJS.Timeout | null = null
  return (...args: any[]) => {
    if (timer) clearTimeout(timer)
    timer = setTimeout(() => {
      fn(...args)
    }, delay)
  }
}

const handleSearch = debounce(() => {
  continuationToken.value = undefined
  tokenHistory.value = []
  refresh()
}, 300)

watch(searchTerm, () => {
  handleSearch()
})

const taskStore = useTaskManagerStore()

type ObjectRow = {
  Key: string
  type: 'prefix' | 'object'
  Size: number
  LastModified: string
}

const bucketName = computed(() => props.bucket)
const prefix = computed(() => decodeURIComponent(props.path))
const pageSize = computed(() => {
  const q = route.query.pageSize
  const s = Array.isArray(q) ? q[0] : q
  const size = Number.parseInt(s ?? '', 10)
  return Number.isFinite(size) && size > 0 ? size : 25
})

const bucketPath = (path?: string | string[]) => {
  const value = Array.isArray(path) ? path.join('/') : path
  return joinRelativeURL('/browser', encodeURIComponent(bucketName.value), value ? encodeURIComponent(value) : '')
}

const continuationToken = ref<string | undefined>(undefined)
const tokenHistory = ref<string[]>([])
const nextToken = ref<string | undefined>(undefined)

const infoRef = ref<{ openDrawer: (bucket: string, key: string) => void }>()
const message = useMessage()
const objectApi = useObject({ bucket: bucketName.value })

const handleNewObject = (asPrefix: boolean) => {
  newObjectAsPrefix.value = asPrefix
  newObjectFormVisible.value = true
}

const handleObjectDeleted = () => {
  refresh()
}

const fetchObjects = async (): Promise<ObjectRow[]> => {
  loading.value = true
  try {
    const command = new ListObjectsV2Command({
      Bucket: bucketName.value,
      Prefix: prefix.value,
      Delimiter: '/',
      ContinuationToken: continuationToken.value,
      MaxKeys: pageSize.value,
    })

    if (showDeleted.value) {
      command.middlewareStack.add(
        next => async args => {
          const request = args.request as HttpRequest
          request.headers['X-Rustfs-Include-Deleted'] = 'true'
          return next(args)
        },
        { step: 'build', name: 'includeDeletedObjectsMiddleware', tags: ['INCLUDE_DELETED'] }
      )
    }

    const response = await $s3Client.send(command)

    nextToken.value = response.NextContinuationToken

    const prefixItems: ObjectRow[] = (response.CommonPrefixes ?? []).map(item => ({
      Key: item.Prefix ?? '',
      type: 'prefix' as const,
      Size: 0,
      LastModified: '',
    }))

    const objectItems: ObjectRow[] = (response.Contents ?? []).map(item => ({
      Key: item.Key ?? '',
      type: 'object' as const,
      Size: item.Size ?? 0,
      LastModified: item.LastModified ? item.LastModified.toISOString() : '',
    }))

    return [...prefixItems, ...objectItems]
  } finally {
    // 200ms delay to avoid flickering
    setTimeout(() => {
      loading.value = false
    }, 200)
  }
}

const asyncDataCacheKey = computed(() => {
  return `objects-${bucketName.value}-${prefix.value}-${continuationToken.value || 'start'}-${searchTerm.value || 'all'}-${
    showDeleted.value ? 'withDeleted' : 'withoutDeleted'
  }`
})

const displayKey = (key: string) => {
  if (!prefix.value) return key
  return key.startsWith(prefix.value) ? key.slice(prefix.value.length) : key
}

const { data, refresh } = await useAsyncData<ObjectRow[]>(
  asyncDataCacheKey,
  async () => {
    const objects = await fetchObjects()
    const term = searchTerm.value.toLowerCase()

    return objects.filter(item => {
      if (term) {
        const key = displayKey(item.Key).toLowerCase()
        return key.includes(term)
      }
      return item.Key !== prefix.value
    })
  },
  {
    default: () => [],
    watch: [bucketName, prefix, continuationToken, searchTerm, showDeleted],
  }
)

watch(showDeleted, () => {
  continuationToken.value = undefined
  tokenHistory.value = []
  refresh()
})

const columns = computed<ColumnDef<ObjectRow, any>[]>(() => {
  return [
    {
      id: 'object',
      header: () => t('Object'),
      accessorFn: row => {
        const key = row.Key ?? ''
        return prefix.value ? key.substring(prefix.value.length) : key
      },
      cell: ({ row }: any) => {
        const key = row.original.Key ?? ''
        const displayKey = prefix.value ? key.substring(prefix.value.length) : key

        let label: string | VNode = displayKey || '/'

        if (row.original.type === 'prefix') {
          return h(
            NuxtLink,
            {
              href: bucketPath(row.original.Key),
              class: 'flex items-center gap-2 text-blue-500 hover:underline',
            },
            {
              default: () => [h(Icon, { name: 'ri:folder-line', class: 'size-4' }), h('span', label)],
            }
          )
        }
        return h(
          'button',
          {
            class: 'flex items-center gap-2 text-primary hover:underline',
            onClick: () => infoRef.value?.openDrawer(bucketName.value, row.original.Key),
          },
          [h(Icon, { name: 'ri:file-line', class: 'size-4' }), h('span', label)]
        )
      },
    },
    {
      id: 'size',
      header: () => t('Size'),
      accessorFn: row => (row.type === 'object' ? row.Size : -1),
      cell: ({ row }: any) => (row.original.type === 'object' ? formatBytes(row.original.Size) : '-'),
    },
    {
      id: 'lastModified',
      header: () => t('Last Modified'),
      accessorFn: row => {
        if (row.type === 'prefix' || !row.LastModified) return ''
        return new Date(row.LastModified).getTime()
      },
      cell: ({ row }: any) =>
        row.original.LastModified ? dayjs(row.original.LastModified).format('YYYY-MM-DD HH:mm:ss') : '-',
    },
    {
      id: 'actions',
      header: () => t('Actions'),
      enableSorting: false,
      cell: ({ row }: any) =>
        h('div', { class: 'flex items-center gap-2' }, [
          row.original.type === 'object'
            ? h(
                Button,
                {
                  variant: 'outline',
                  size: 'sm',
                  onClick: () => downloadFile(row.original.Key),
                },
                () => [h(Icon, { name: 'ri:download-cloud-2-line', class: 'size-4' }), h('span', t('Download'))]
              )
            : null,
          h(
            Button,
            {
              variant: 'outline',
              size: 'sm',
              onClick: () => confirmDelete([row.original.Key]),
            },
            () => [h(Icon, { name: 'ri:delete-bin-5-line', class: 'size-4' }), h('span', t('Delete'))]
          ),
        ]),
    },
  ]
})

const { table, selectedRowIds } = useDataTable<ObjectRow>({
  data,
  columns,
  getRowId: (row: any) => row.Key,
  enableRowSelection: true,
  manualPagination: true,
})

// Use selectedRowIds from data-table instead of manually maintaining checkedKeys
const checkedKeys = computed(() => selectedRowIds.value)

// 监听任务完成事件，只在所有任务完成时刷新列表
// 这样可以避免在上传/删除大量文件时频繁刷新
// 保存事件处理函数引用，以便在卸载时正确清理
const handleAllTasksCompleted = () => {
  refresh()
}

onMounted(() => {
  // 监听所有任务全部完成事件（上传/删除）
  taskStore.on('drained', handleAllTasksCompleted)
})

onUnmounted(() => {
  // 清理事件监听器
  taskStore.off('drained', handleAllTasksCompleted)
})

const goToNextPage = () => {
  if (!nextToken.value) return
  if (continuationToken.value) {
    tokenHistory.value.push(continuationToken.value)
  }
  continuationToken.value = nextToken.value
  refresh()
}

const goToPreviousPage = () => {
  const prev = tokenHistory.value.pop()
  continuationToken.value = prev
  refresh()
}

const handleRefresh = () => {
  refresh()
}

const computeRelativeKey = (key: string) => {
  if (!key) return ''
  const base = prefix.value || ''
  return base && key.startsWith(base) ? key.slice(base.length) : key
}

const collectKeysForDeletion = async (keys: string[]) => {
  const rows = data.value ?? []
  const rowMap = new Map(rows.map(item => [item.Key, item]))
  const collected: string[] = []

  for (const key of keys) {
    if (!key) continue
    const row = rowMap.get(key)
    if (row?.type === 'prefix') {
      await objectApi.mapAllFiles(bucketName.value, row.Key, fileKey => {
        if (fileKey) {
          collected.push(fileKey)
        }
      })
    } else {
      collected.push(key)
    }
  }

  return Array.from(new Set(collected))
}

const downloadFile = async (key: string) => {
  if (!key) return
  const loadingMsg = message.loading(t('Getting URL'), { duration: 0 })
  try {
    const url = await objectApi.getSignedUrl(key)
    fetch(url).then(async response => {
      const filename = key.split('/').pop() || ''
      // 获取头信息，将 Headers 对象转换为普通对象
      // 如果服务器没有返回 content-type，根据文件扩展名推断
      const headers: any = {
        'content-type': getContentType(response.headers, filename),
        filename: response.headers.get('content-disposition')?.split('filename=')[1] || '',
      }
      let blob = await response.blob()
      exportFile({ headers, data: blob }, filename)
    })
  } catch (error: any) {
    message.error(error?.message || t('Download Failed'))
  } finally {
    loadingMsg.destroy()
  }
}

const downloadMultiple = async () => {
  if (!checkedKeys.value.length) {
    message.warning(t('Please select at least one item'))
    return
  }

  const selectedRows = (data.value ?? []).filter(item => checkedKeys.value.includes(item.Key))
  if (!selectedRows.length) {
    message.warning(t('No files to download'))
    return
  }

  const collecting = message.loading(t('Collecting files'), { duration: 0 })
  const allFiles: { key: string; relative: string }[] = []

  try {
    for (const item of selectedRows) {
      if (item.type === 'object') {
        const relative = computeRelativeKey(item.Key)
        allFiles.push({ key: item.Key, relative })
      } else if (item.type === 'prefix') {
        await objectApi.mapAllFiles(bucketName.value, item.Key, fileKey => {
          const relative = computeRelativeKey(fileKey)
          allFiles.push({ key: fileKey, relative })
        })
      }
    }
  } catch (error: any) {
    collecting.destroy()
    message.error(error?.message || t('Download Failed'))
    return
  }

  collecting.destroy()

  if (!allFiles.length) {
    message.warning(t('No files to download'))
    return
  }

  const zip = new JSZip()
  let finished = 0
  let destroyProgress: (() => void) | null | undefined

  const updateProgress = () => {
    if (destroyProgress) destroyProgress()
    const handle = message.loading(`${t('Downloading files')} ${Math.round((finished / allFiles.length) * 100)}%`, {
      duration: 0,
    })
    destroyProgress = handle.destroy
  }

  updateProgress()

  try {
    await Promise.all(
      allFiles.map(async ({ key, relative }) => {
        const url = await objectApi.getSignedUrl(key)
        const response = await fetch(url)
        const blob = await response.blob()
        zip.file(relative || key, blob)
        finished++
        updateProgress()
      })
    )
  } catch (error: any) {
    if (destroyProgress) destroyProgress()
    message.error(error?.message || t('Download Failed'))
    return
  }

  if (destroyProgress) destroyProgress()

  const content = await zip.generateAsync({ type: 'blob' })
  saveAs(content, `${bucketName.value || 'download'}.zip`)
  message.success(t('Download ready'))
}

const confirmDelete = (keys: string[]) => {
  dialog.error({
    title: t('Warning'),
    content: t('Are you sure you want to delete the selected objects?'),
    positiveText: t('Confirm'),
    negativeText: t('Cancel'),
    onPositiveClick: () => handleDelete(keys),
  })
}

const handleDelete = async (keys: string[]) => {
  try {
    const targets = await collectKeysForDeletion(keys)
    if (!targets.length) {
      message.success(t('Delete Success'))
    } else {
      taskStore.addDeleteKeys(targets, bucketName.value)
      message.success(t('Delete task created'))
    }
    table.resetRowSelection()
    refresh()
  } catch (error: any) {
    message.error(error?.message || t('Delete Failed'))
  }
}

const handleBatchDelete = () => {
  if (!checkedKeys.value.length) {
    message.warning(t('Please select at least one item'))
    return
  }
  confirmDelete([...checkedKeys.value])
}

const formatBytes = (bytes: number) => {
  if (bytes === 0) return '0 B'
  const units = ['B', 'KB', 'MB', 'GB', 'TB']
  const i = Math.floor(Math.log(bytes) / Math.log(1024))
  return `${(bytes / 1024 ** i).toFixed(2)} ${units[i]}`
}
</script>
