// components/object/path-links.vue
<template>
  <div class="flex items-center gap-2">
    <div class="flex items-center">
      <template v-for="segment in displaySegments">
        <span class="text-gray-500">&nbsp;/&nbsp;</span>
        <button
          @click="() => handleOnClick(segment)"
          :class="{ 'text-blue-500 hover:underline': segment.index > -1, 'cursor-default': segment.index === -1 }"
        >
          {{ segment.value }}
        </button>
      </template>
    </div>
    <Button
      v-if="props.objectKey"
      variant="ghost"
      size="sm"
      class="shrink-0"
      @click="copy(fullPath)"
      :title="t('Copy Path')"
    >
      <Icon v-if="!copied" :size="16" name="ri:file-copy-line" />
      <Icon v-else :size="16" name="ri:check-line" class="text-green-600" />
      <span class="sr-only">{{ t('Copy Path') }}</span>
    </Button>
  </div>
</template>

<script lang="ts" setup>
import { Button } from '@/components/ui/button'
import { Icon } from '#components'
import { computed } from 'vue'
import { useI18n } from 'vue-i18n'

const { t } = useI18n()

const props = defineProps<{
  objectKey: string
  bucketName?: string
  onClick: (path: string) => any
}>()

const fullPath = computed(() => {
  if (props.bucketName) {
    return `${props.bucketName}/${props.objectKey}`
  }
  return props.objectKey
})

const segments = computed(() =>
  props.objectKey
    .split('/')
    .filter(Boolean)
    .map((item, index) => {
      return {
        value: item,
        index,
      }
    })
)

const { copy, copied } = useClipboard({ copiedDuring: 3000 })

const displaySegments = computed(() => {
  if (segments.value.length <= 6) {
    return segments.value
  }

  return [...segments.value.slice(0, 3), { value: '...', index: -1 }, ...segments.value.slice(-3)]
})

const handleOnClick = (segment: { value: string; index: number }) => {
  if (segment.index === -1) {
    return
  }

  const path = segments.value
    .slice(0, segment.index + 1)
    .map(item => item.value)
    .join('/')
  props.onClick(path)
}
</script>

// components/object/path-links.tsx
"use client"

import * as React from "react"
import { useTranslation } from "react-i18next"
import { Button } from "@/components/ui/button"
import { copyToClipboard } from "@/lib/clipboard"
import { RiFileCopyLine, RiCheckLine } from "@remixicon/react"

interface Segment {
  value: string
  index: number
}

interface ObjectPathLinksProps {
  objectKey: string
  bucketName?: string
  onClick: (path: string) => void
}

function useClipboard(value: string, copiedDuring = 3000) {
  const [copied, setCopied] = React.useState(false)

  const copy = React.useCallback(async () => {
    try {
      await copyToClipboard(value)
      setCopied(true)
      setTimeout(() => setCopied(false), copiedDuring)
    } catch {
      setCopied(false)
    }
  }, [value, copiedDuring])

  return { copy, copied }
}

export function ObjectPathLinks({ objectKey, bucketName, onClick }: ObjectPathLinksProps) {
  const { t } = useTranslation()
  const fullPath = bucketName ? `${bucketName}/${objectKey}` : objectKey
  const { copy, copied } = useClipboard(fullPath)

  const segments: Segment[] = objectKey
    .split("/")
    .filter(Boolean)
    .map((item, index) => ({ value: item, index }))

  const displaySegments: Segment[] =
    segments.length <= 6 ? segments : [...segments.slice(0, 3), { value: "...", index: -1 }, ...segments.slice(-3)]

  const handleClick = (segment: Segment) => {
    if (segment.index === -1) return
    const path = segments
      .slice(0, segment.index + 1)
      .map((s) => s.value)
      .join("/")
    onClick(path)
  }

  return (
    <div className="flex items-center gap-2">
      <div className="flex items-center">
        {displaySegments.map((segment) => (
          <React.Fragment key={segment.index}>
            <span className="text-muted-foreground">&nbsp;/&nbsp;</span>
            <button
              type="button"
              onClick={() => handleClick(segment)}
              className={segment.index > -1 ? "text-blue-500 hover:underline" : "cursor-default"}
            >
              {segment.value}
            </button>
          </React.Fragment>
        ))}
      </div>
      {objectKey ? (
        <Button variant="ghost" size="sm" className="shrink-0" onClick={copy} title={t("Copy Path")}>
          {copied ? <RiCheckLine className="size-4 text-green-600" /> : <RiFileCopyLine className="size-4" />}
          <span className="sr-only">{t("Copy Path")}</span>
        </Button>
      ) : null}
    </div>
  )
}
