// components/object/preview-modal.tsx
"use client"

import * as React from "react"
import { useTranslation } from "react-i18next"
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { Spinner } from "@/components/ui/spinner"
import { Button } from "@/components/ui/button"

const TEXT_MIMES = [
  "application/json",
  "application/xml",
  "application/javascript",
  "text/plain",
  "text/html",
  "text/css",
  "text/csv",
  "text/markdown",
]
const TEXT_EXTENSIONS = [".txt", ".json", ".xml", ".js", ".ts", ".css", ".md", ".html", ".csv", ".yml", ".yaml"]
const ALLOWED_SIZE = 1024 * 1024 * 2 // 2MB

interface ObjectPreviewModalProps {
  show: boolean
  onShowChange: (show: boolean) => void
  object: {
    ContentType?: string
    ContentLength?: number
    Key?: string
    SignedUrl?: string
  } | null
}

export function ObjectPreviewModal({ show, onShowChange, object }: ObjectPreviewModalProps) {
  const { t } = useTranslation()
  const [textContent, setTextContent] = React.useState("")
  const [loading, setLoading] = React.useState(false)
  const [isFormatted, setIsFormatted] = React.useState(true)

  const contentType = object?.ContentType ?? ""
  const previewUrl = object?.SignedUrl ?? ""
  const objectSize = Number(object?.ContentLength ?? 0)
  const objectKey = object?.Key ?? ""

  const isImage = contentType.startsWith("image/")
  const isVideo = contentType.startsWith("video/")
  const isAudio = contentType.startsWith("audio/")
  const isPdf = contentType === "application/pdf" || objectKey.toLowerCase().endsWith(".pdf")
  const isJson = contentType === "application/json" || objectKey.toLowerCase().endsWith(".json")
  const isText =
    objectSize <= ALLOWED_SIZE &&
    (TEXT_MIMES.some((m) => contentType.startsWith(m)) ||
      TEXT_EXTENSIONS.some((ext) => objectKey.toLowerCase().endsWith(ext)))

  const getFormattedContent = () => {
    if (!isJson || !isFormatted) return textContent
    try {
      const parsed = JSON.parse(textContent)
      return JSON.stringify(parsed, null, 2)
    } catch {
      return textContent
    }
  }

  React.useEffect(() => {
    if (show && isText && previewUrl) {
      setLoading(true)
      setIsFormatted(true)
      fetch(previewUrl)
        .then((r) => r.text())
        .then(setTextContent)
        .catch(() => setTextContent(t("Preview unavailable")))
        .finally(() => setLoading(false))
    } else if (!show) {
      setTextContent("")
      setLoading(false)
    }
  }, [show, isText, previewUrl, t])

  return (
    <Dialog open={show} onOpenChange={onShowChange}>
      <DialogContent className="sm:max-w-4xl max-h-[85vh] overflow-auto z-[1000]">
        <DialogHeader>
          <DialogTitle className="flex items-start justify-between mr-6">{t("Preview")}</DialogTitle>
        </DialogHeader>
        <div className="min-h-[300px] rounded-md border p-4 flex flex-col">
          {loading ? (
            <Spinner className="mx-auto size-8 text-muted-foreground" />
          ) : (
            <>
              {isImage && (
                <div className="flex justify-center">
                  {/* eslint-disable-next-line @next/next/no-img-element */}
                  <img src={previewUrl} alt="preview" className="max-h-[60vh]" />
                </div>
              )}
              {isPdf && <iframe src={previewUrl} className="h-[70vh] w-full" frameBorder={0} title="PDF preview" />}
              {isText && (
                <pre className="max-h-[70vh] relative overflow-auto whitespace-pre-wrap break-words">
                  {getFormattedContent()}
                  <div className="absolute right-0 top-0">
                    {isJson && (
                      <div className="flex justify-end">
                        <Button variant="outline" size="sm" onClick={() => setIsFormatted(!isFormatted)}>
                          {isFormatted ? t("Raw") : t("Formatted")}
                        </Button>
                      </div>
                    )}
                  </div>
                </pre>
              )}
              {isVideo && (
                <video controls className="w-full">
                  <source src={previewUrl} type={contentType} />
                  {t("Your browser does not support the video tag")}
                </video>
              )}
              {isAudio && (
                <audio controls className="w-full">
                  <source src={previewUrl} type={contentType} />
                  {t("Your browser does not support the audio tag")}
                </audio>
              )}
              {!isImage && !isPdf && !isText && !isVideo && !isAudio && object && (
                <div className="flex flex-1 justify-center items-center text-sm text-muted-foreground">
                  {t("Cannot Preview", {
                    contentType: contentType || "unknown",
                  })}
                </div>
              )}
            </>
          )}
        </div>
      </DialogContent>
    </Dialog>
  )
}

// components/object/preview-modal.vue
<template>
  <AppModal v-model="visibleProxy" :title="t('Preview')" size="xl" :close-on-backdrop="false">
    <div class="flex flex-col gap-4">
      <div class="flex items-center justify-end gap-2">
        <Button variant="outline" size="sm" @click="closeModal">
          <Icon name="ri:close-line" class="size-4" />
          {{ t('Close') }}
        </Button>
      </div>
      <div class="min-h-[300px] rounded-md border p-4">
        <AppSpinner v-if="loading" class="mx-auto size-8" />
        <template v-else>
          <div v-if="isImage" class="flex justify-center">
            <img :src="previewUrl" alt="preview" class="max-h-[60vh]" />
          </div>
          <iframe v-else-if="isPdf" :src="previewUrl" class="h-[70vh] w-full" frameborder="0" />
          <pre v-else-if="isText" class="max-h-[70vh] overflow-auto whitespace-pre-wrap wrap-break-word">{{ textContent }}</pre>
          <video v-else-if="isVideo" controls class="w-full">
            <source :src="previewUrl" :type="contentType" />
            {{ t('Your browser does not support the video tag') }}
          </video>
          <audio v-else-if="isAudio" controls class="w-full">
            <source :src="previewUrl" :type="contentType" />
            {{ t('Your browser does not support the audio tag') }}
          </audio>
          <div v-else class="flex h-full items-center justify-center text-sm text-muted-foreground">
            {{ t('Cannot Preview', { contentType: contentType || 'unknown' }) }}
          </div>
        </template>
      </div>
    </div>
  </AppModal>
</template>

<script setup lang="ts">
import { Button } from '@/components/ui/button'

import { AppModal, AppSpinner } from '@/components/app'
import { Icon } from '#components'
import { computed, ref, watch } from 'vue'
import { useI18n } from 'vue-i18n'

const { t } = useI18n()

const TEXT_MIMES = [
  'application/json',
  'application/xml',
  'application/javascript',
  'text/plain',
  'text/html',
  'text/css',
  'text/csv',
  'text/markdown',
]
const TEXT_EXTENSIONS = ['.txt', '.json', '.xml', '.js', '.ts', '.css', '.md', '.html', '.csv', '.yml', '.yaml']
const ALLOWED_SIZE = 1024 * 1024 * 2 // 2MB

const props = defineProps<{
  show: boolean
  object: any
}>()

const emit = defineEmits<{
  (e: 'update:show', value: boolean): void
}>()

const visibleProxy = computed({
  get: () => props.show,
  set: value => emit('update:show', value),
})

const contentType = computed(() => props.object?.ContentType || '')
const previewUrl = computed(() => props.object?.SignedUrl || '')
const objectSize = computed(() => Number(props.object?.ContentLength ?? 0))
const objectKey = computed(() => props.object?.Key || '')

const isImage = computed(() => contentType.value.startsWith('image/'))
const isVideo = computed(() => contentType.value.startsWith('video/'))
const isAudio = computed(() => contentType.value.startsWith('audio/'))
const isPdf = computed(() => contentType.value === 'application/pdf' || objectKey.value.endsWith('.pdf'))
const isText = computed(() => {
  if (objectSize.value > ALLOWED_SIZE) return false
  return (
    TEXT_MIMES.some(mime => contentType.value.startsWith(mime)) ||
    TEXT_EXTENSIONS.some(ext => objectKey.value.toLowerCase().endsWith(ext))
  )
})

const loading = ref(false)
const textContent = ref('')

watch(
  () => props.show,
  value => {
    if (value) loadContent()
    else reset()
  }
)

const loadContent = async () => {
  if (!props.object) return
  if (!isText.value) {
    textContent.value = ''
    return
  }

  loading.value = true
  try {
    const response = await fetch(previewUrl.value)
    textContent.value = await response.text()
  } catch (error) {
    textContent.value = t('Preview unavailable')
  } finally {
    loading.value = false
  }
}

const reset = () => {
  loading.value = false
  textContent.value = ''
}

const closeModal = () => emit('update:show', false)
</script>
