// components/object/versions.vue
<template>
  <Modal v-model="visibleProxy" :title="t('Object Versions')" size="lg" :close-on-backdrop="false">
    <div class="space-y-4 z-20">
      <DataTable :table="table" :is-loading="loading" :empty-title="t('No Versions')" />
      <div class="flex justify-end">
        <Button variant="outline" @click="closeModal">{{ t('Close') }}</Button>
      </div>
    </div>
  </Modal>
</template>

<script setup lang="ts">
import { Button } from '@/components/ui/button'

import DataTable from '@/components/data-table/data-table.vue'
import { useDataTable } from '@/components/data-table/useDataTable'
import { GetObjectCommand } from '@aws-sdk/client-s3'
import { getSignedUrl } from '@aws-sdk/s3-request-presigner'
import type { ColumnDef } from '@tanstack/vue-table'
import dayjs from 'dayjs'
import { computed, h, ref, watch } from 'vue'
import { useI18n } from 'vue-i18n'
import Modal from '~/components/modal.vue'

const props = defineProps<{
  bucketName: string
  objectKey: string
  visible: boolean
}>()

const emit = defineEmits<{
  (e: 'close'): void
  (e: 'preview', versionId: string): void
  (e: 'refresh-parent'): void
}>()

const { t } = useI18n()
const message = useMessage()
const ActionButton = Button as unknown as any

const visibleProxy = computed({
  get: () => props.visible,
  set: value => {
    if (!value) emit('close')
  },
})

const versions = ref<any[]>([])
const loading = ref(false)

const objectApi = useObject({ bucket: props.bucketName })

const columns = computed<ColumnDef<any, any>[]>(() => [
  {
    id: 'versionId',
    header: () => t('VersionId'),
    cell: ({ row }: any) => shortVersionId(row.original.VersionId),
  },
  {
    id: 'lastModified',
    header: () => t('LastModified'),
    cell: ({ row }: any) =>
      row.original.LastModified ? dayjs(row.original.LastModified).format('YYYY-MM-DD HH:mm:ss') : '',
  },
  {
    id: 'size',
    header: () => t('Size'),
    cell: ({ row }: any) => (typeof row.original.Size === 'number' ? formatBytes(row.original.Size) : ''),
  },
  {
    id: 'actions',
    header: () => t('Action'),
    cell: ({ row }: any) =>
      h('div', { class: 'flex gap-2' }, [
        h(
          ActionButton,
          {
            variant: 'outline',
            size: 'sm',
            onClick: () => previewVersion(row.original),
          },
          () => t('Preview')
        ),
        h(
          ActionButton,
          {
            variant: 'outline',
            size: 'sm',
            onClick: () => downloadVersion(row.original),
          },
          () => t('Download')
        ),
        h(
          ActionButton,
          {
            variant: 'destructive',
            size: 'sm',
            class: 'text-white',
            onClick: () => deleteVersion(row.original),
          },
          () => t('Delete')
        ),
      ]),
  },
])

const { table } = useDataTable({
  data: versions,
  columns,
})

watch(
  () => props.visible,
  value => {
    if (value) fetchVersions()
  }
)

const fetchVersions = async () => {
  loading.value = true
  try {
    const response = await objectApi.listObjectVersions(props.objectKey)
    versions.value = response.Versions
  } catch (error) {
    message.error(t('Failed to fetch versions'))
    versions.value = []
  } finally {
    loading.value = false
  }
}

const shortVersionId = (versionId: string) => {
  if (!versionId) return ''
  const parts = versionId.split(/[-./]/)
  return parts[parts.length - 1]
}

const formatBytes = (bytes: number) => {
  if (bytes === 0) return '0 B'
  const k = 1024
  const sizes = ['B', 'KB', 'MB', 'GB', 'TB', 'PB']
  const i = Math.floor(Math.log(bytes) / Math.log(k))
  return `${parseFloat((bytes / k ** i).toFixed(2))} ${sizes[i]}`
}

const previewVersion = (row: any) => emit('preview', row.VersionId)

const downloadVersion = async (row: any) => {
  const url = await getSignedUrlWithVersion(props.objectKey, row.VersionId)
  window.open(url, '_blank')
}

const deleteVersion = async (row: any) => {
  try {
    await objectApi.deleteObject(props.objectKey, row.VersionId)
    message.success(t('Delete Success'))
    fetchVersions()
    emit('refresh-parent')
  } catch (error: any) {
    message.error(error?.message || t('Delete Failed'))
  }
}

const getSignedUrlWithVersion = async (key: string, versionId: string, expiresIn = 3600) => {
  const client = useNuxtApp().$s3Client
  const command = new GetObjectCommand({
    Bucket: props.bucketName,
    Key: key,
    VersionId: versionId,
  })
  return await getSignedUrl(client, command, { expiresIn })
}

const closeModal = () => emit('close')
</script>

// components/object/versions.tsx
"use client"

import * as React from "react"
import { useTranslation } from "react-i18next"
import { RiFileCopyLine, RiEyeLine, RiDownloadCloud2Line, RiDeleteBin5Line } from "@remixicon/react"
import { Button } from "@/components/ui/button"
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { DataTable } from "@/components/data-table/data-table"
import { useDataTable } from "@/hooks/use-data-table"
import { useObject } from "@/hooks/use-object"
import { useMessage } from "@/lib/feedback/message"
import { exportFile } from "@/lib/export-file"
import { getContentType } from "@/lib/mime-types"
import { formatBytes } from "@/lib/functions"
import { GetObjectCommand } from "@aws-sdk/client-s3"
import { getSignedUrl } from "@aws-sdk/s3-request-presigner"
import { useS3 } from "@/contexts/s3-context"
import type { ColumnDef } from "@tanstack/react-table"
import dayjs from "dayjs"

interface VersionRow {
  VersionId?: string
  LastModified?: Date
  Size?: number
  Key?: string
}

interface ObjectVersionsProps {
  bucketName: string
  objectKey: string
  visible: boolean
  onClose: () => void
  onPreview: (versionId: string) => void
  onRefreshParent: () => void
}

export function ObjectVersions({
  bucketName,
  objectKey,
  visible,
  onClose,
  onPreview,
  onRefreshParent,
}: ObjectVersionsProps) {
  const { t } = useTranslation()
  const message = useMessage()
  const objectApi = useObject(bucketName)
  const client = useS3()

  const [versions, setVersions] = React.useState<VersionRow[]>([])
  const [loading, setLoading] = React.useState(false)

  const fetchVersions = React.useCallback(async () => {
    if (!objectKey) return
    setLoading(true)
    try {
      const response = await objectApi.listObjectVersions(objectKey)
      setVersions((response as { Versions?: VersionRow[] }).Versions ?? [])
    } catch {
      message.error(t("Failed to fetch versions"))
      setVersions([])
    } finally {
      setLoading(false)
    }
  }, [objectKey, objectApi, message, t])

  React.useEffect(() => {
    if (visible) fetchVersions()
  }, [visible, fetchVersions])

  const copyVersionId = React.useCallback(
    async (versionId: string) => {
      if (!versionId) return
      try {
        await navigator.clipboard.writeText(versionId)
        message.success(t("Copy Success"))
      } catch {
        message.error(t("Copy Failed"))
      }
    },
    [message, t],
  )

  const getSignedUrlWithVersion = React.useCallback(
    async (key: string, versionId: string, expiresIn = 3600) => {
      const command = new GetObjectCommand({
        Bucket: bucketName,
        Key: key,
        VersionId: versionId === "00000000-0000-0000-0000-000000000000" ? undefined : versionId,
      })
      return getSignedUrl(client, command, { expiresIn })
    },
    [bucketName, client],
  )

  const downloadVersion = React.useCallback(
    async (row: VersionRow) => {
      const versionId = row.VersionId ?? ""
      try {
        const url = await getSignedUrlWithVersion(objectKey, versionId)
        const response = await fetch(url)
        const filename = objectKey.split("/").pop() ?? ""
        const headers: Record<string, string> = {
          "content-type": getContentType(response.headers, filename),
          filename: response.headers.get("content-disposition")?.split("filename=")[1] ?? "",
        }
        const blob = await response.blob()
        exportFile({ headers, data: blob }, filename)
      } catch (err) {
        message.error((err as Error)?.message ?? t("Download Failed"))
      }
    },
    [getSignedUrlWithVersion, objectKey, message, t],
  )

  const deleteVersion = React.useCallback(
    async (row: VersionRow) => {
      const versionId = row.VersionId
      if (!versionId) return
      try {
        await objectApi.deleteObject(objectKey, versionId)
        message.success(t("Delete Success"))
        fetchVersions()
        onRefreshParent()
      } catch (err) {
        message.error((err as Error)?.message ?? t("Delete Failed"))
      }
    },
    [objectApi, objectKey, message, t, fetchVersions, onRefreshParent],
  )

  const columns: ColumnDef<VersionRow>[] = React.useMemo(
    () => [
      {
        id: "versionId",
        header: () => t("VersionId"),
        cell: ({ row }) => {
          const versionId = row.original.VersionId ?? ""
          return (
            <div className="flex items-center gap-2">
              <span className="font-mono text-sm">{versionId}</span>
              <Button
                variant="ghost"
                size="sm"
                className="h-6 w-6 p-0 shrink-0"
                onClick={() => copyVersionId(versionId)}
                title={t("Copy")}
              >
                <RiFileCopyLine className="size-3.5" />
              </Button>
            </div>
          )
        },
      },
      {
        id: "lastModified",
        header: () => t("LastModified"),
        cell: ({ row }) =>
          row.original.LastModified ? dayjs(row.original.LastModified).format("YYYY-MM-DD HH:mm:ss") : "",
      },
      {
        id: "size",
        header: () => t("Size"),
        cell: ({ row }) => (typeof row.original.Size === "number" ? formatBytes(row.original.Size) : ""),
      },
      {
        id: "actions",
        header: () => t("Action"),
        cell: ({ row }) => (
          <div className="flex gap-2">
            <Button variant="outline" size="sm" onClick={() => onPreview(row.original.VersionId ?? "")}>
              <RiEyeLine className="size-4" />
              {t("Preview")}
            </Button>
            <Button variant="outline" size="sm" onClick={() => downloadVersion(row.original)}>
              <RiDownloadCloud2Line className="size-4" />
              {t("Download")}
            </Button>
            <Button variant="destructive" size="sm" className="text-white" onClick={() => deleteVersion(row.original)}>
              <RiDeleteBin5Line className="size-4" />
              {t("Delete")}
            </Button>
          </div>
        ),
      },
    ],
    [t, onPreview, copyVersionId, downloadVersion, deleteVersion],
  )

  const { table } = useDataTable<VersionRow>({
    data: versions,
    columns,
  })

  return (
    <Dialog open={visible} onOpenChange={(open) => !open && onClose()}>
      <DialogContent className="sm:max-w-4xl max-h-[80vh] overflow-auto">
        <DialogHeader>
          <DialogTitle>{t("Object Versions")}</DialogTitle>
        </DialogHeader>
        <DataTable table={table} isLoading={loading} emptyTitle={t("No Versions")} />
      </DialogContent>
    </Dialog>
  )
}
