// components/app-top-nav.vue
<template>
  <header
    class="flex h-16 shrink-0 items-center gap-2 justify-between border-b bg-background transition-[height] ease-linear backdrop-blur group-has-data-[collapsible=icon]/sidebar-wrapper:h-12">
    <div class="flex items-center gap-2">
      <SidebarTrigger class="-ml-1" />
    </div>
    <div class="flex items-center gap-2">
      <LanguageSwitcher />
      <ThemeSwitcher />
      <LinksGithub />
      <LinksX />
      <UserDropdown />
    </div>
  </header>
</template>

// components/app-top-nav.tsx
"use client"

import { SidebarTrigger } from "@/components/ui/sidebar"
import { ThemeSwitcher } from "@/components/theme-switcher"
import { LanguageSwitcher } from "@/components/language-switcher"
import { LinksGithub } from "@/components/links/github"
import { LinksX } from "@/components/links/x"
import { UserDropdown } from "@/components/user-dropdown"

export function AppTopNav() {
  return (
    <header className="flex h-16 shrink-0 items-center justify-between gap-2 border-b bg-background transition-[height] ease-linear backdrop-blur group-has-data-[collapsible=icon]/sidebar-wrapper:h-12">
      <div className="flex items-center gap-2">
        <SidebarTrigger className="-ml-1" />
      </div>
      <div className="flex items-center gap-2">
        <LanguageSwitcher />
        <ThemeSwitcher />
        <LinksGithub />
        <LinksX />
        <UserDropdown />
      </div>
    </header>
  )
}
