// components/copy-input.tsx
"use client"

import * as React from "react"
import { useTranslation } from "react-i18next"
import { RiFileCopyLine } from "@remixicon/react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { useMessage } from "@/lib/ui/message"
import { cn } from "@/lib/utils"

interface CopyInputProps extends Omit<React.ComponentProps<typeof Input>, "value" | "onChange"> {
  value?: string
  onChange?: (value: string) => void
  readonly?: boolean
  copyIcon?: boolean
  className?: string
}

export function CopyInput({
  value = "",
  onChange,
  readonly = false,
  copyIcon = false,
  className,
  ...props
}: CopyInputProps) {
  const { t } = useTranslation()
  const message = useMessage()

  const handleCopy = async () => {
    try {
      if (!value) throw new Error("No value to copy")
      await navigator.clipboard.writeText(value)
      message.success(t("Copy Success"))
    } catch {
      message.error(t("Copy Failed"))
    }
  }

  return (
    <div className={cn("flex h-full items-center gap-2", className)}>
      <Input
        value={value}
        onChange={(e) => onChange?.(e.target.value)}
        readOnly={readonly}
        className="flex-1"
        {...props}
      />
      {!copyIcon ? (
        <Button type="button" variant="default" onClick={handleCopy}>
          {t("Copy")}
        </Button>
      ) : (
        <Button
          type="button"
          variant="ghost"
          size="sm"
          className="shrink-0 outline"
          title={t("Copy")}
          onClick={handleCopy}
        >
          <RiFileCopyLine className="size-[18px]" />
          <span className="sr-only">{t("Copy")}</span>
        </Button>
      )}
    </div>
  )
}

// components/copy-input.vue
<script lang="ts" setup>
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'

import { Icon } from '#components'
import { useMessage } from '@/lib/ui/message'
import ClipboardJS from 'clipboard'
import { onMounted, onUnmounted, ref } from 'vue'
import { useI18n } from 'vue-i18n'

const { t } = useI18n()

const props = defineProps({
  readonly: {
    type: Boolean,
    default: false,
  },
  copyIcon: {
    type: Boolean,
    default: false,
  },
  id: {
    type: String,
    required: false,
    default: () => {
      return `copy-input-${Math.random().toString(36).substring(2, 15)}`
    },
  },
})

const model = defineModel<string>()

const message = useMessage()
const clipboard = ref<ClipboardJS | null>(null)

onMounted(() => {
  clipboard.value = new ClipboardJS(
    props.copyIcon ? `#${props.id}-btn-icon` : `#${props.id}-btn`
  )

  clipboard.value.on('success', function (e) {
    message.success(t('Copy Success'))
    e.clearSelection()
  })

  clipboard.value.on('error', async function () {
    // 如果复制失败，则使用 navigator.clipboard.writeText 进行复制
    try {
      if (navigator.clipboard && model.value) {
        await navigator.clipboard.writeText(model.value)
        message.success(t('Copy Success'))
      } else {
        message.error(t('Copy Failed'))
      }
    } catch {
      message.error(t('Copy Failed'))
    }
  })
})

onUnmounted(() => {
  clipboard.value?.destroy()
  clipboard.value = null
})
</script>

<template>
  <div class="flex h-full items-center gap-2">
    <Input v-model="model" :readonly="props.readonly" :id="props.id" class="flex-1" />
    <Button v-if="!props.copyIcon" :id="`${props.id}-btn`" :data-clipboard-target="`#${props.id}`" variant="default">
      {{ t('Copy') }}
    </Button>
    <Button v-else :id="`${props.id}-btn-icon`" variant="ghost" size="sm" class="shrink-0" :data-clipboard-target="`#${props.id}`" :title="t('Copy')">
      <Icon :size="18" name="ri:file-copy-line" />
      <span class="sr-only">{{ t('Copy') }}</span>
    </Button>
  </div>
</template>
