// components/search-input.tsx
"use client"

import * as React from "react"
import { RiSearchLine, RiCloseLine } from "@remixicon/react"
import { InputGroup, InputGroupAddon, InputGroupButton, InputGroupInput } from "@/components/ui/input-group"
import { cn } from "@/lib/utils"

interface SearchInputProps extends Omit<React.ComponentProps<"input">, "value" | "onChange"> {
  value: string
  onChange: (value: string) => void
  placeholder?: string
  clearable?: boolean
  className?: string
}

export function SearchInput({
  value,
  onChange,
  placeholder = "",
  clearable = false,
  className,
  ...props
}: SearchInputProps) {
  const showClear = clearable && Boolean(value)

  const handleClear = () => {
    onChange("")
  }

  return (
    <InputGroup className={cn("w-full", className)} {...props}>
      <InputGroupAddon className="text-muted-foreground">
        <RiSearchLine className="size-4" />
      </InputGroupAddon>
      <InputGroupInput value={value} onChange={(e) => onChange(e.target.value)} placeholder={placeholder} />
      {showClear && (
        <InputGroupButton variant="ghost" size="icon-xs" type="button" aria-label="Clear" onClick={handleClear}>
          <RiCloseLine className="size-4" />
        </InputGroupButton>
      )}
    </InputGroup>
  )
}

// components/search-input.vue
<script setup lang="ts">
import { Icon } from '#components'
import { InputGroup, InputGroupAddon, InputGroupButton, InputGroupInput } from '@/components/ui/input-group'
import { cn } from '@/lib/utils'
import type { HTMLAttributes } from 'vue'
import { computed, useAttrs } from 'vue'

const modelValue = defineModel<string>({ default: '' })

const props = withDefaults(
  defineProps<{
    placeholder?: string
    icon?: string
    groupClass?: HTMLAttributes['class']
    inputClass?: HTMLAttributes['class']
    addonClass?: HTMLAttributes['class']
    clearable?: boolean
  }>(),
  {
    placeholder: '',
    icon: 'ri:search-line',
    groupClass: undefined,
    inputClass: undefined,
    addonClass: undefined,
    clearable: false,
  }
)

const attrs = useAttrs()

const showClear = computed(() => props.clearable && Boolean(modelValue.value))

const handleClear = () => {
  modelValue.value = ''
}
</script>

<template>
  <InputGroup v-bind="attrs" :class="cn('w-full', groupClass)">
    <InputGroupAddon :class="cn('text-muted-foreground', addonClass)">
      <Icon :name="icon" class="size-4" />
    </InputGroupAddon>
    <InputGroupInput v-model="modelValue" :placeholder="placeholder" :class="inputClass" />
    <InputGroupButton v-if="showClear" variant="ghost" size="icon-xs" aria-label="Clear" @click="handleClear">
      <Icon name="ri:close-line" class="size-4" />
    </InputGroupButton>
    <slot />
  </InputGroup>
</template>
