// app/(dashboard)/user-groups/page.tsx
"use client"

import * as React from "react"
import { useState, useEffect } from "react"
import { useTranslation } from "react-i18next"
import {
  RiAddLine,
  RiDeleteBin5Line,
  RiEdit2Line,
  RiGroup2Fill,
} from "@remixicon/react"
import { Button } from "@/components/ui/button"
import { SearchInput } from "@/components/search-input"
import { Page } from "@/components/page"
import { PageHeader } from "@/components/page-header"
import { DataTable } from "@/components/data-table/data-table"
import { DataTablePagination } from "@/components/data-table/data-table-pagination"
import { useDataTable } from "@/hooks/use-data-table"
import { UserGroupNewForm } from "@/components/user-group/user-group-new-form"
import { UserGroupEditForm } from "@/components/user-group/user-group-edit-form"
import { UserGroupSetPoliciesMultiple } from "@/components/user-group/user-group-set-policies-multiple"
import { useGroups } from "@/hooks/use-groups"
import { useDialog } from "@/lib/ui/dialog"
import { useMessage } from "@/lib/ui/message"
import type { ColumnDef } from "@tanstack/react-table"

interface GroupRow {
  name: string
}

export default function UserGroupsPage() {
  const { t } = useTranslation()
  const message = useMessage()
  const dialog = useDialog()
  const { listGroup, getGroup, removeGroup } = useGroups()

  const [data, setData] = useState<GroupRow[]>([])
  const [loading, setLoading] = useState(false)
  const [searchTerm, setSearchTerm] = useState("")
  const [newFormOpen, setNewFormOpen] = useState(false)
  const [editFormOpen, setEditFormOpen] = useState(false)
  const [editRow, setEditRow] = useState<GroupRow | null>(null)
  const [policiesDialogOpen, setPoliciesDialogOpen] = useState(false)

  const getDataList = async () => {
    setLoading(true)
    try {
      const res = (await listGroup()) as string[] | undefined
      setData(
        (res ?? []).map((name) => ({
          name,
        }))
      )
    } catch {
      message.error(t("Failed to get data"))
    } finally {
      setLoading(false)
      table.resetRowSelection()
    }
  }

  useEffect(() => {
    getDataList()
  }, [])

  const filteredData = React.useMemo(() => {
    if (!searchTerm) return data
    const term = searchTerm.toLowerCase()
    return data.filter((row) => row.name.toLowerCase().includes(term))
  }, [data, searchTerm])

  const columns: ColumnDef<GroupRow>[] = React.useMemo(
    () => [
      {
        accessorKey: "name",
        header: () => t("Name"),
        cell: ({ row }) => (
          <span className="font-medium">{row.original.name}</span>
        ),
        filterFn: "includesString",
      },
      {
        id: "actions",
        header: () => t("Actions"),
        enableSorting: false,
        enableHiding: false,
        meta: { width: 200 },
        cell: ({ row }) => (
          <div className="flex items-center gap-2">
            <Button
              type="button"
              size="sm"
              variant="outline"
              onClick={() => openEditItem(row.original)}
            >
              <RiEdit2Line className="size-4" />
              <span>{t("Edit")}</span>
            </Button>
            <Button
              type="button"
              size="sm"
              variant="outline"
              onClick={() => confirmDelete(row.original)}
            >
              <RiDeleteBin5Line className="size-4" />
              <span>{t("Delete")}</span>
            </Button>
          </div>
        ),
      },
    ],
    [t]
  )

  const { table, selectedRowIds } = useDataTable<GroupRow>({
    data: filteredData,
    columns,
    getRowId: (row) => row.name,
    enableRowSelection: true,
  })

  const selectedKeys = Array.from(selectedRowIds)

  const openEditItem = (row: GroupRow) => {
    setEditRow(row)
    setEditFormOpen(true)
  }

  const confirmDelete = (row: GroupRow) => {
    dialog.error({
      title: t("Confirm Delete"),
      content: "",
      positiveText: t("Delete"),
      negativeText: t("Cancel"),
      onPositiveClick: () => deleteItem(row),
    })
  }

  const deleteItem = async (row: GroupRow) => {
    try {
      const info = (await getGroup(row.name)) as { members?: string[] }
      if (info?.members?.length) {
        message.error(t("Please remove members first"))
        return
      }
      await removeGroup(row.name)
      message.success(t("Delete Success"))
      await getDataList()
    } catch {
      message.error(t("Delete Failed"))
    }
  }

  return (
    <Page>
      <PageHeader
        actions={
          <>
            <SearchInput
              value={searchTerm}
              onChange={setSearchTerm}
              placeholder={t("Search User Group")}
              clearable
              className="max-w-md"
            />
            <Button
              type="button"
              variant="outline"
              disabled={!selectedKeys.length}
              onClick={() => setPoliciesDialogOpen(true)}
            >
              <RiGroup2Fill className="size-4" />
              {t("Assign Policy")}
            </Button>
            <Button
              type="button"
              variant="outline"
              onClick={() => setNewFormOpen(true)}
            >
              <RiAddLine className="size-4" />
              {t("Add User Group")}
            </Button>
          </>
        }
      >
        <h1 className="text-2xl font-bold">{t("User Groups")}</h1>
      </PageHeader>

      <div className="space-y-4">
        <DataTable
          table={table}
          isLoading={loading}
          emptyTitle={t("No Data")}
          emptyDescription={t("Create user groups to organize permissions")}
          tableClass="min-w-full"
        />
        <DataTablePagination table={table} />

        <UserGroupNewForm
          open={newFormOpen}
          onOpenChange={setNewFormOpen}
          onSuccess={getDataList}
        />
        <UserGroupEditForm
          open={editFormOpen}
          onOpenChange={setEditFormOpen}
          row={editRow}
          onSuccess={getDataList}
        />
        <UserGroupSetPoliciesMultiple
          checkedKeys={selectedKeys}
          open={policiesDialogOpen}
          onOpenChange={setPoliciesDialogOpen}
          onChangePoliciesSuccess={getDataList}
        />
      </div>
    </Page>
  )
}

// pages/user-groups/index.vue
<template>
  <page>
    <page-header>
      <h1 class="text-2xl font-bold">{{ t('User Groups') }}</h1>
      <template #actions>
        <SearchInput v-model="searchTerm" :placeholder="t('Search User Group')" clearable class="w-full max-w-md" />
        <Button type="button" variant="outline" :disabled="!selectedKeys.length" @click="allocationPolicy">
          <Icon class="size-4" name="ri:group-2-fill" />
          {{ t('Assign Policy') }}
        </Button>
        <Button type="button" variant="outline" @click="addUserGroup">
          <Icon class="size-4" name="ri:add-line" />
          {{ t('Add User Group') }}
        </Button>
      </template>
    </page-header>

    <DataTable
      :table="table"
      :is-loading="loading"
      :empty-title="t('No Data')"
      :empty-description="t('Create user groups to organize permissions.')"
      table-class="min-w-full"
    />
    <DataTablePagination :table="table" class="px-2 py-3" />

    <user-group-edit-form ref="editItemRef" />
    <user-group-new-form ref="newItemRef" v-model:visible="newItemVisible" @search="getDataList" />
    <user-group-set-policies-mutiple
      ref="policiesRef"
      :checkedKeys="selectedKeys"
      @changePoliciesSuccess="changePoliciesSuccess"
    />
  </page>
</template>

<script setup lang="ts">
import { Icon } from '#components'
import DataTablePagination from '@/components/data-table/data-table-pagination.vue'
import DataTable from '@/components/data-table/data-table.vue'
import { useDataTable } from '@/components/data-table/useDataTable'
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger,
} from '@/components/ui/alert-dialog'
import { Button } from '@/components/ui/button'
import type { ColumnDef } from '@tanstack/vue-table'
import { computed, h, onMounted, ref, watch } from 'vue'
import { useI18n } from 'vue-i18n'

const { t } = useI18n()

const dialog = useDialog()
const message = useMessage()
const group = useGroups()

interface GroupRow {
  name: string
}

const searchTerm = ref('')
const listData = ref<GroupRow[]>([])
const loading = ref(false)

const columns: ColumnDef<GroupRow>[] = [
  {
    accessorKey: 'name',
    header: () => t('Name'),
    cell: ({ row }) => h('span', { class: 'font-medium' }, row.original.name),
    filterFn: 'includesString',
  },
  {
    id: 'actions',
    header: () => t('Actions'),
    enableSorting: false,
    enableHiding: false,
    meta: {
      width: 200,
    },
    cell: ({ row }) =>
      h('div', { class: 'flex items-center gap-2' }, [
        h(
          Button,
          {
            type: 'button',
            size: 'sm',
            variant: 'outline',
            onClick: () => openEditItem(row.original),
          },
          () => [h(Icon, { class: 'size-4', name: 'ri:edit-2-line' }), h('span', t('Edit'))]
        ),
        h(
          AlertDialog,
          {},
          {
            default: () => [
              h(
                AlertDialogTrigger,
                { asChild: true },
                {
                  default: () =>
                    h(
                      Button,
                      {
                        type: 'button',
                        size: 'sm',
                        variant: 'outline',
                      },
                      () => [h(Icon, { class: 'size-4', name: 'ri:delete-bin-5-line' }), h('span', t('Delete'))]
                    ),
                }
              ),
              h(
                AlertDialogContent,
                {},
                {
                  default: () => [
                    h(AlertDialogHeader, {}, { default: () => h(AlertDialogTitle, {}, () => t('Confirm Delete')) }),
                    h(
                      AlertDialogFooter,
                      {},
                      {
                        default: () => [
                          h(AlertDialogCancel, {}, () => t('Cancel')),
                          h(
                            AlertDialogAction,
                            {
                              onClick: () => deleteItem(row.original),
                            },
                            () => t('Delete')
                          ),
                        ],
                      }
                    ),
                  ],
                }
              ),
            ],
          }
        ),
      ]),
  },
]

const { table, selectedRows, selectedRowIds } = useDataTable<GroupRow>({
  data: listData,
  columns,
  getRowId: row => row.name,
  enableRowSelection: true,
})

// 选中的行数据可以直接使用 selectedRows
// 如果需要 ID 数组，可以使用 selectedRowIds，或者手动提取
const selectedKeys = computed(() => selectedRows.value.map(row => row.name))

onMounted(() => {
  getDataList()
})

const getDataList = async () => {
  loading.value = true
  try {
    const res = await group.listGroup()
    listData.value =
      res?.map((item: string) => ({
        name: item,
      })) || []
  } catch (error) {
    message.error(t('Failed to get data'))
  } finally {
    loading.value = false
  }
  table.resetRowSelection()
}

const newItemRef = ref()
const newItemVisible = ref(false)

function addUserGroup() {
  newItemVisible.value = true
}

const policiesRef = ref()
const allocationPolicy = () => {
  policiesRef.value.openDialog()
}

const changePoliciesSuccess = () => {
  table.resetRowSelection()
}

const editItemRef = ref()
function openEditItem(row: GroupRow) {
  editItemRef.value.openDialog(row)
}

async function deleteItem(row: GroupRow) {
  try {
    const info = await group.getGroup(row.name)
    if (info.members.length) {
      message.error(t('Please remove members first'))
      return
    }
    await group.updateGroupMembers({
      group: row.name,
      members: info.members,
      isRemove: true,
      groupStatus: 'enabled',
    })
    message.success(t('Delete Success'))
    await getDataList()
  } catch (error) {
    message.error(t('Delete Failed'))
  }
}

function deleteByList() {
  dialog.error({
    title: t('Warning'),
    content: t('Are you sure you want to delete all selected user groups?'),
    positiveText: t('Confirm'),
    negativeText: t('Cancel'),
    onPositiveClick: async () => {
      if (!selectedKeys.value.length) {
        message.error(t('Please select at least one item'))
        return
      }
      try {
        await Promise.all(selectedKeys.value.map(item => group.removeGroup(item)))
        table.resetRowSelection()
        message.success(t('Delete Success'))
        await getDataList()
      } catch (error) {
        message.error(t('Delete Failed'))
      }
    },
  })
}

watch(searchTerm, value => {
  table.getColumn('name')?.setFilterValue(value || undefined)
})
</script>
