// app/(auth)/auth/login/page.tsx
"use client"

import { useEffect, Suspense } from "react"
import Link from "next/link"
import Image from "next/image"
import { useSearchParams } from "next/navigation"
import { useRouter } from "next/navigation"
import { useTranslation } from "react-i18next"
import { RiSettings3Line } from "@remixicon/react"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs"
import {
  Field,
  FieldContent,
  FieldLabel,
} from "@/components/ui/field"
import { ThemeSwitcher } from "@/components/theme-switcher"
import { LanguageSwitcher } from "@/components/language-switcher"
import { AuthHerosStatic } from "@/components/auth/heros/static"
import { useAuth } from "@/contexts/auth-context"
import { useMessage } from "@/lib/ui/message"
import { buildRoute } from "@/lib/routes"
import logoImage from "@/assets/logo.svg"
import { configManager } from "@/lib/config"
import { useState } from "react"

type LoginMethod = "accessKeyAndSecretKey" | "sts"

export default function LoginPage() {
  return (
    <Suspense fallback={<div className="min-h-screen bg-background" />}>
      <LoginPageContent />
    </Suspense>
  )
}

function LoginPageContent() {
  const router = useRouter()
  const searchParams = useSearchParams()
  const message = useMessage()
  const { login, isAuthenticated } = useAuth()
  const { t } = useTranslation()

  const [method, setMethod] = useState<LoginMethod>("accessKeyAndSecretKey")
  const [accessKeyAndSecretKey, setAccessKeyAndSecretKey] = useState({
    accessKeyId: "",
    secretAccessKey: "",
  })
  const [sts, setSts] = useState({
    accessKeyId: "",
    secretAccessKey: "",
    sessionToken: "",
  })

  useEffect(() => {
    if (isAuthenticated) {
      router.replace("/")
    }
  }, [isAuthenticated, router])

  useEffect(() => {
    if (searchParams.get("unauthorized") === "true") {
      message.warning(t("Your session has expired. Please log in again."))
      router.replace("/auth/login")
    }
  }, [searchParams, message, t, router])

  const handleLogin = async (e: React.FormEvent) => {
    e.preventDefault()

    const credentials =
      method === "accessKeyAndSecretKey"
        ? accessKeyAndSecretKey
        : sts

    try {
      const currentConfig = await configManager.loadConfig()
      await login(credentials, currentConfig)

      message.success(t("Login Success"))
      window.location.href = buildRoute("/")
    } catch {
      message.error(t("Login Failed"))
    }
  }

  return (
    <LoginForm
      method={method}
      setMethod={setMethod}
      accessKeyAndSecretKey={accessKeyAndSecretKey}
      setAccessKeyAndSecretKey={setAccessKeyAndSecretKey}
      sts={sts}
      setSts={setSts}
      handleLogin={handleLogin}
    />
  )
}

function LoginForm({
  method,
  setMethod,
  accessKeyAndSecretKey,
  setAccessKeyAndSecretKey,
  sts,
  setSts,
  handleLogin,
}: {
  method: LoginMethod
  setMethod: (m: LoginMethod) => void
  accessKeyAndSecretKey: { accessKeyId: string; secretAccessKey: string }
  setAccessKeyAndSecretKey: React.Dispatch<
    React.SetStateAction<{ accessKeyId: string; secretAccessKey: string }>
  >
  sts: { accessKeyId: string; secretAccessKey: string; sessionToken: string }
  setSts: React.Dispatch<
    React.SetStateAction<{
      accessKeyId: string
      secretAccessKey: string
      sessionToken: string
    }>
  >
  handleLogin: (e: React.FormEvent) => void
}) {
  const { t } = useTranslation()

  return (
    <div className="relative flex min-h-screen flex-col items-center justify-center bg-gray-100 dark:bg-neutral-800 lg:p-20">
      <Image
        src={buildRoute("/backgrounds/scillate.svg")}
        alt=""
        fill
        className="absolute inset-0 z-0 opacity-45 object-cover"
      />
      <div className="z-10 mx-auto flex max-h-[85vh] w-full max-w-7xl flex-1 flex-col overflow-hidden rounded-lg shadow-lg dark:border-neutral-700 dark:bg-neutral-800 lg:flex-row">
        <div className="hidden w-1/2 lg:block">
          <AuthHerosStatic />
        </div>
        <div className="relative flex w-full flex-col items-center justify-center bg-white dark:border-neutral-700 dark:bg-neutral-900 lg:w-1/2">
          <div className="absolute right-4 top-4 z-10">
            <Link
              href="/config"
              className="inline-flex h-8 w-8 items-center justify-center rounded-lg border border-gray-200 bg-white text-gray-600 shadow-sm transition-colors hover:bg-gray-50 hover:text-gray-800 dark:border-neutral-700 dark:bg-neutral-900 dark:text-neutral-400 dark:hover:bg-neutral-800 dark:hover:text-white"
              title={t("Server Configuration")}
            >
              <RiSettings3Line className="text-sm" />
            </Link>
          </div>

          <div className="max-w-sm w-full space-y-6 p-4 sm:p-7">
            <Image
              src={logoImage}
              alt="RustFS"
              width={112}
              height={24}
              className="max-w-28"
            />

            <div className="space-y-4">
              <Tabs
                value={method}
                onValueChange={(v) => setMethod(v as LoginMethod)}
                className="flex flex-col gap-4"
              >
                <TabsList className="w-full">
                  <TabsTrigger className="w-1/2" value="accessKeyAndSecretKey">
                    {t("Key Login")}
                  </TabsTrigger>
                  <TabsTrigger className="w-1/2" value="sts">
                    {t("STS Login")}
                  </TabsTrigger>
                </TabsList>

                <form onSubmit={handleLogin} autoComplete="off">
                  <div className="grid gap-y-6">
                    {method === "accessKeyAndSecretKey" ? (
                      <>
                        <Field>
                          <FieldLabel htmlFor="accessKey">
                            {t("Account")}
                          </FieldLabel>
                          <FieldContent>
                            <Input
                              id="accessKey"
                              value={accessKeyAndSecretKey.accessKeyId}
                              onChange={(e) =>
                                setAccessKeyAndSecretKey((prev) => ({
                                  ...prev,
                                  accessKeyId: e.target.value,
                                }))
                              }
                              autoComplete="username"
                              type="text"
                              placeholder={t("Please enter account")}
                            />
                          </FieldContent>
                        </Field>
                        <Field>
                          <FieldLabel htmlFor="secretKey">{t("Key")}</FieldLabel>
                          <FieldContent>
                            <Input
                              id="secretKey"
                              value={accessKeyAndSecretKey.secretAccessKey}
                              onChange={(e) =>
                                setAccessKeyAndSecretKey((prev) => ({
                                  ...prev,
                                  secretAccessKey: e.target.value,
                                }))
                              }
                              autoComplete="current-password"
                              type="password"
                              placeholder={t("Please enter key")}
                            />
                          </FieldContent>
                        </Field>
                      </>
                    ) : (
                      <>
                        <Field>
                          <FieldLabel htmlFor="stsAccessKey">
                            {t("STS Username")}
                          </FieldLabel>
                          <FieldContent>
                            <Input
                              id="stsAccessKey"
                              value={sts.accessKeyId}
                              onChange={(e) =>
                                setSts((prev) => ({
                                  ...prev,
                                  accessKeyId: e.target.value,
                                }))
                              }
                              autoComplete="new-password"
                              type="text"
                              placeholder={t("Please enter STS username")}
                            />
                          </FieldContent>
                        </Field>
                        <Field>
                          <FieldLabel htmlFor="stsSecretKey">
                            {t("STS Key")}
                          </FieldLabel>
                          <FieldContent>
                            <Input
                              id="stsSecretKey"
                              value={sts.secretAccessKey}
                              onChange={(e) =>
                                setSts((prev) => ({
                                  ...prev,
                                  secretAccessKey: e.target.value,
                                }))
                              }
                              autoComplete="new-password"
                              type="password"
                              placeholder={t("Please enter STS key")}
                            />
                          </FieldContent>
                        </Field>
                        <Field>
                          <FieldLabel htmlFor="sessionToken">
                            {t("STS Session Token")}
                          </FieldLabel>
                          <FieldContent>
                            <Input
                              id="sessionToken"
                              value={sts.sessionToken}
                              onChange={(e) =>
                                setSts((prev) => ({
                                  ...prev,
                                  sessionToken: e.target.value,
                                }))
                              }
                              autoComplete="new-password"
                              type="text"
                              placeholder={t(
                                "Please enter STS session token"
                              )}
                            />
                          </FieldContent>
                        </Field>
                      </>
                    )}

                    <Button
                      type="submit"
                      variant="default"
                      className="w-full justify-center"
                    >
                      {t("Login")}
                    </Button>
                  </div>
                </form>
              </Tabs>
            </div>

            <div>
              <p className="text-sm text-gray-600 dark:text-neutral-400">
                {t("Login Problems?")}{" "}
                <Link
                  href="https://www.rustfs.com"
                  className="text-blue-600 hover:underline"
                >
                  {t("Get Help")}
                </Link>
              </p>
            </div>

            <div className="mx-auto flex w-1/2 items-center justify-around gap-4">
              <div className="inline-flex">
                <ThemeSwitcher />
              </div>
              <div className="inline-flex">
                <LanguageSwitcher />
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

// pages/auth/login.vue
<script lang="ts" setup>
import { Input } from '@/components/ui/input'
import { Button } from '@/components/ui/button'

await setPageLayout('plain')

import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { Field, FieldContent, FieldLabel } from '@/components/ui/field'
import { ref } from 'vue'
import { useI18n } from 'vue-i18n'

const { t } = useI18n()
const method = ref<'accessKeyAndSecretKey' | 'sts'>('accessKeyAndSecretKey')
const accessKeyAndSecretKey = ref({
  accessKeyId: '',
  secretAccessKey: '',
})

const sts = ref({
  accessKeyId: '',
  secretAccessKey: '',
  sessionToken: '',
})

const message = useMessage()
const auth = useAuth()

const handleLogin = async () => {
  const credentials = method.value === 'accessKeyAndSecretKey' ? accessKeyAndSecretKey.value : sts.value

  try {
    // 使用配置管理器获取配置（优先使用localStorage中的配置）
    const { configManager } = await import('~/utils/config')
    const currentConfig = await configManager.loadConfig()

    await auth.login(credentials, currentConfig)

    message.success(t('Login Success'))
    // 重新加载页面以确保新的配置生效
    window.location.reload()
  } catch (error) {
    message.error(t('Login Failed'))
  }
}
</script>

<template>
  <div class="lg:p-20 flex flex-col items-center justify-center min-h-screen bg-gray-100 dark:bg-neutral-800">
    <img src="~/assets/backgrounds/scillate.svg" class="absolute inset-0 z-0 opacity-45" alt="" />
    <div class="flex-1 flex w-full z-10 max-w-7xl lg:max-h-[85vh] shadow-lg rounded-lg overflow-hidden mx-auto dark:bg-neutral-800 dark:border-neutral-700">
      <div class="hidden lg:block w-1/2">
        <auth-heros-static></auth-heros-static>
      </div>
      <div class="w-full lg:w-1/2 flex flex-col justify-center items-center bg-white dark:bg-neutral-900 dark:border-neutral-700 relative">
        <!-- 表单容器右上角的配置按钮 -->
        <div class="absolute top-4 right-4 z-10">
          <NuxtLink to="/config"
            class="inline-flex items-center justify-center w-8 h-8 rounded-lg border border-gray-200 bg-white text-gray-600 shadow-sm hover:bg-gray-50 hover:text-gray-800 dark:bg-neutral-900 dark:border-neutral-700 dark:text-neutral-400 dark:hover:bg-neutral-800 dark:hover:text-white transition-colors"
            :title="t('Server Configuration')">
            <Icon name="ri:settings-3-line" class="text-sm" />
          </NuxtLink>
        </div>

        <div class="max-w-sm w-full p-4 sm:p-7 space-y-6">
          <img src="~/assets/logo.svg" class="max-w-28" alt="" />

          <div class="space-y-4">
            <Tabs v-model="method" class="flex flex-col gap-4">
              <TabsList class="w-full">
                <TabsTrigger class="w-1/2" value="accessKeyAndSecretKey">{{ t('Key Login') }}</TabsTrigger>
                <TabsTrigger class="w-1/2" value="sts">{{ t('STS Login') }}</TabsTrigger>
              </TabsList>
            </Tabs>

            <!-- Form -->
            <form @submit.prevent="handleLogin" autocomplete="off">
              <div class="grid gap-y-6">
                <template v-if="method == 'accessKeyAndSecretKey'">
                  <Field>
                    <FieldLabel for="accessKey">{{ t('Account') }}</FieldLabel>
                    <FieldContent>
                      <Input id="accessKey" v-model="accessKeyAndSecretKey.accessKeyId" autocomplete="new-password" type="text" :placeholder="t('Please enter account')" />
                    </FieldContent>
                  </Field>
                  <Field>
                    <FieldLabel for="secretKey">{{ t('Key') }}</FieldLabel>
                    <FieldContent>
                      <Input id="secretKey" v-model="accessKeyAndSecretKey.secretAccessKey" autocomplete="new-password" type="password" :placeholder="t('Please enter key')" />
                    </FieldContent>
                  </Field>
                </template>

                <template v-else>
                  <Field>
                    <FieldLabel for="stsAccessKey">{{ t('STS Username') }}</FieldLabel>
                    <FieldContent>
                      <Input id="stsAccessKey" v-model="sts.accessKeyId" autocomplete="new-password" type="text" :placeholder="t('Please enter STS username')" />
                    </FieldContent>
                  </Field>
                  <Field>
                    <FieldLabel for="stsSecretKey">
                      {{ t('STS Key') }}
                    </FieldLabel>
                    <FieldContent>
                      <Input id="stsSecretKey" v-model="sts.secretAccessKey" autocomplete="new-password" type="password" :placeholder="t('Please enter STS key')" />
                    </FieldContent>
                  </Field>
                  <Field>
                    <FieldLabel for="sessionToken">
                      {{ t('STS Session Token') }}
                    </FieldLabel>
                    <FieldContent>
                      <Input id="sessionToken" v-model="sts.sessionToken" autocomplete="new-password" type="text" :placeholder="t('Please enter STS session token')" />
                    </FieldContent>
                  </Field>
                </template>

                <Button type="submit" variant="default" class="w-full justify-center">
                  {{ t('Login') }}
                </Button>
              </div>
            </form>
            <!-- End Form -->
          </div>

          <div class="">
            <p class="text-sm text-gray-600 dark:text-neutral-400">
              {{ t('Login Problems?') }}
              <NuxtLink to="https://www.rustfs.com" class="text-blue-600 hover:underline">{{ t('Get Help') }}</NuxtLink>
            </p>
          </div>

          <div class="flex items-center justify-around gap-4 w-1/2 mx-auto">
            <div class="inline-flex">
              <theme-switcher />
            </div>
            <div class="inline-flex">
              <language-switcher />
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>
