// components/providers/AppUiProvider.vue
<template>
  <slot />
  <AppDialogHost />
  <ClientOnly>
    <Toaster position="top-center" :rich-colors="true" :close-button="true" />
  </ClientOnly>
</template>

<script setup lang="ts">
import AppDialogHost from '@/components/providers/AppDialogHost.vue'
import { Toaster } from '@/components/ui/sonner'
import { createDialogController, dialogControllerKey } from '@/lib/ui/dialog'
import { createMessageApi, messageInjectionKey } from '@/lib/ui/message'
import { provide } from 'vue'

const dialogController = createDialogController()
const messageApi = createMessageApi()

provide(dialogControllerKey, dialogController)
provide(messageInjectionKey, messageApi)
</script>

// components/providers/app-ui-provider.tsx
"use client"

import { Toaster } from "@/components/ui/sonner"
import { MessageProvider } from "@/lib/ui/message"
import { DialogProvider } from "@/lib/ui/dialog"
import { DialogHost } from "@/components/dialog-host"

export function AppUiProvider({ children }: { children: React.ReactNode }) {
  return (
    <MessageProvider>
      <DialogProvider>
        {children}
        <DialogHost />
        <Toaster position="top-center" richColors closeButton />
      </DialogProvider>
    </MessageProvider>
  )
}
