// components/user/change-password.tsx
"use client"

import { useState } from "react"
import { useTranslation } from "react-i18next"
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from "@/components/ui/dialog"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Spinner } from "@/components/ui/spinner"
import { Field, FieldContent, FieldLabel, FieldDescription } from "@/components/ui/field"
import { useMessage } from "@/lib/feedback/message"
import { useApiOptional } from "@/contexts/api-context"
import { useUsers } from "@/hooks/use-users"

interface ChangePasswordProps {
  visible: boolean
  onVisibleChange: (visible: boolean) => void
}

export function ChangePassword({ visible, onVisibleChange }: ChangePasswordProps) {
  const { t } = useTranslation()
  const message = useMessage()
  const api = useApiOptional()
  const { createUser } = useUsers()

  const [currentSecretKey, setCurrentSecretKey] = useState("")
  const [newSecretKey, setNewSecretKey] = useState("")
  const [reNewSecretKey, setReNewSecretKey] = useState("")
  const [errors, setErrors] = useState({
    current: "",
    new: "",
    reNew: "",
  })
  const [submitting, setSubmitting] = useState(false)

  const clearForm = () => {
    setCurrentSecretKey("")
    setNewSecretKey("")
    setReNewSecretKey("")
    setErrors({ current: "", new: "", reNew: "" })
    setSubmitting(false)
  }

  const closeModal = (open = false) => {
    onVisibleChange(open)
    if (!open) clearForm()
  }

  const validate = () => {
    const newErrors = {
      current: !currentSecretKey ? t("Please enter current password") : "",
      new: !newSecretKey ? t("Please enter new password") : "",
      reNew: !reNewSecretKey
        ? t("Please enter new password again")
        : reNewSecretKey !== newSecretKey
          ? t("The two passwords are inconsistent")
          : "",
    }
    setErrors(newErrors)
    return !newErrors.current && !newErrors.new && !newErrors.reNew
  }

  const submitForm = async () => {
    if (!validate()) {
      message.error(t("Please fill in the correct format"))
      return
    }

    setSubmitting(true)
    try {
      if (!api) {
        message.error(t("API not ready"))
        return
      }
      const userInfo = (await api.get("/accountinfo")) as { account_name?: string }
      await createUser({
        accessKey: userInfo?.account_name ?? "",
        secretKey: newSecretKey,
        status: "enabled",
      })
      message.success(t("Updated successfully"))
      closeModal()
    } catch (error) {
      console.error(error)
      message.error(t("Update failed"))
    } finally {
      setSubmitting(false)
    }
  }

  return (
    <Dialog open={visible} onOpenChange={closeModal}>
      <DialogContent className="sm:max-w-lg">
        <DialogHeader>
          <DialogTitle>{t("Change current account password")}</DialogTitle>
        </DialogHeader>

        <div className="space-y-4 py-4">
          <Field>
            <FieldLabel htmlFor="password-current">
              {t("Current Password")}
            </FieldLabel>
            <FieldContent>
              <Input
                id="password-current"
                value={currentSecretKey}
                onChange={(e) => setCurrentSecretKey(e.target.value)}
                type="password"
                autoComplete="off"
              />
            </FieldContent>
            {errors.current && (
              <FieldDescription className="text-destructive">
                {errors.current}
              </FieldDescription>
            )}
          </Field>

          <Field>
            <FieldLabel htmlFor="password-new">{t("New Password")}</FieldLabel>
            <FieldContent>
              <Input
                id="password-new"
                value={newSecretKey}
                onChange={(e) => setNewSecretKey(e.target.value)}
                type="password"
                autoComplete="off"
              />
            </FieldContent>
            {errors.new && (
              <FieldDescription className="text-destructive">
                {errors.new}
              </FieldDescription>
            )}
          </Field>

          <Field>
            <FieldLabel htmlFor="password-new-confirm">
              {t("Confirm New Password")}
            </FieldLabel>
            <FieldContent>
              <Input
                id="password-new-confirm"
                value={reNewSecretKey}
                onChange={(e) => setReNewSecretKey(e.target.value)}
                type="password"
                autoComplete="off"
                disabled={!newSecretKey}
              />
            </FieldContent>
            {errors.reNew && (
              <FieldDescription className="text-destructive">
                {errors.reNew}
              </FieldDescription>
            )}
          </Field>
        </div>

        <DialogFooter>
          <Button variant="outline" onClick={() => closeModal()}>
            {t("Cancel")}
          </Button>
          <Button onClick={submitForm} disabled={submitting}>
            {submitting ? <Spinner className="size-4" /> : null}
            <span>{t("Submit")}</span>
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  )
}

// components/access-keys/change-password.vue
<script setup lang="ts">
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Spinner } from '@/components/ui/spinner'

import { Field, FieldContent, FieldDescription, FieldLabel } from '@/components/ui/field'
import { computed, reactive, ref } from 'vue'
import { useI18n } from 'vue-i18n'
import Modal from '~/components/modal.vue'
const { createUser } = useUsers()

const { t } = useI18n()

interface Props {
  visible: boolean
}
const { visible } = defineProps<Props>()

const emit = defineEmits<Emits>()
const formModel = reactive({
  current_secret_key: '',
  new_secret_key: '',
  re_new_secret_key: '',
})

const errors = reactive({
  current_secret_key: '',
  new_secret_key: '',
  re_new_secret_key: '',
})

const submitting = ref(false)
const message = useMessage()
const { $api } = useNuxtApp()

const modalVisible = computed({
  get() {
    return visible
  },
  set(value) {
    closeModal(value)
  },
})

interface Emits {
  (e: 'update:visible', visible: boolean): void
}

function clearForm() {
  formModel.current_secret_key = ''
  formModel.new_secret_key = ''
  formModel.re_new_secret_key = ''
  Object.keys(errors).forEach(key => {
    errors[key as keyof typeof errors] = ''
  })
}

function closeModal(visible = false) {
  emit('update:visible', visible)
  if (!visible) {
    clearForm()
    submitting.value = false
  }
}

function validate() {
  errors.current_secret_key = formModel.current_secret_key ? '' : t('Please enter current password')
  errors.new_secret_key = formModel.new_secret_key ? '' : t('Please enter new password')

  if (!formModel.re_new_secret_key) {
    errors.re_new_secret_key = t('Please enter new password again')
  } else if (formModel.re_new_secret_key !== formModel.new_secret_key) {
    errors.re_new_secret_key = t('The two passwords are inconsistent')
  } else {
    errors.re_new_secret_key = ''
  }

  return !errors.current_secret_key && !errors.new_secret_key && !errors.re_new_secret_key
}

async function submitForm() {
  if (!validate()) {
    message.error(t('Please fill in the correct format'))
    return
  }

  submitting.value = true
  try {
    const userInfo = await $api.get(`/accountinfo`)
    await createUser({
      accessKey: userInfo.account_name,
      secretKey: formModel.new_secret_key,
      status: 'enabled',
    })
    message.success(t('Updated successfully'))
    closeModal()
  } catch (error) {
    console.error(error)
    message.error(t('Update failed'))
  } finally {
    submitting.value = false
  }
}
</script>

<template>
  <Modal v-model="modalVisible" :title="t('Change current account password')" size="md" :close-on-backdrop="false">
    <div class="space-y-4">
      <Field>
        <FieldLabel for="password-current">{{ t('Current Password') }}</FieldLabel>
        <FieldContent>
          <Input id="password-current" v-model="formModel.current_secret_key" type="password" autocomplete="off" />
        </FieldContent>
        <FieldDescription v-if="errors.current_secret_key" class="text-destructive">
          {{ errors.current_secret_key }}
        </FieldDescription>
      </Field>

      <Field>
        <FieldLabel for="password-new">{{ t('New Password') }}</FieldLabel>
        <FieldContent>
          <Input id="password-new" v-model="formModel.new_secret_key" type="password" autocomplete="off" />
        </FieldContent>
        <FieldDescription v-if="errors.new_secret_key" class="text-destructive">
          {{ errors.new_secret_key }}
        </FieldDescription>
      </Field>

      <Field>
        <FieldLabel for="password-new-confirm">{{ t('Confirm New Password') }}</FieldLabel>
        <FieldContent>
          <Input
            id="password-new-confirm"
            v-model="formModel.re_new_secret_key"
            type="password"
            autocomplete="off"
            :disabled="!formModel.new_secret_key"
          />
        </FieldContent>
        <FieldDescription v-if="errors.re_new_secret_key" class="text-destructive">
          {{ errors.re_new_secret_key }}
        </FieldDescription>
      </Field>
    </div>

    <template #footer>
      <div class="flex justify-end gap-2">
        <Button variant="outline" @click="closeModal()">
          {{ t('Cancel') }}
        </Button>
        <Button variant="default" :disabled="submitting" @click="submitForm">
          <Spinner v-if="submitting" class="size-4" />
          <span>{{ t('Submit') }}</span>
        </Button>
      </div>
    </template>
  </Modal>
</template>
