// components/auth/heros/static.tsx
"use client"

import Image from "next/image"
import Link from "next/link"
import { useTranslation } from "react-i18next"
import { RiArrowRightLongFill } from "@remixicon/react"
import { FlipWords } from "@/components/ui/flip-words"

export function AuthHerosStatic() {
  const { t, i18n } = useTranslation()
  const locale = i18n.language?.split("-")[0] ?? "en"

  return (
    <div className="relative flex h-full w-full flex-col justify-center gap-8 overflow-hidden border-r bg-gray-50 p-16 dark:border-none dark:bg-black">
      <div className="z-10 flex max-w-7xl flex-col">
        <Image
          src="/logo.svg"
          alt="RustFS"
          width={112}
          height={24}
          className="max-w-28"
        />
        <div className="my-6 px-0 text-4xl font-semibold text-primary">
          <span className={locale !== "zh" ? "pr-1" : undefined}>
            {t("Rust-based")}{" "}
          </span>
          <FlipWords
            words={[
              t("High Performance"),
              t("Infinite Scaling"),
              t("Secure & Reliable"),
              t("Multi-Cloud Storage"),
              t("S3 Compatible"),
            ]}
            duration={3000}
            className="text-4xl font-semibold text-primary"
          />
          <div className="mt-2 text-muted-foreground">
            {t("Reliable distributed file system")}
          </div>
        </div>
      </div>
      <Link
        href="https://www.rustfs.com"
        className="z-10 inline-flex w-max items-center gap-2 rounded-full border border-blue-500 p-2 px-5 leading-none text-primary-500"
      >
        <span>{t("Visit website")}</span>
        <RiArrowRightLongFill className="mr-2" />
      </Link>
      <div className="absolute inset-0 z-0 h-full">
        <Image
          src="/backgrounds/ttten.svg"
          alt=""
          fill
          className="object-cover opacity-45"
        />
      </div>
    </div>
  )
}

// components/auth/heros/static.vue
<template>
  <div class="w-full bg-gray-50 dark:bg-black h-full p-16 flex flex-col justify-center gap-8 overflow-hidden relative border-r dark:border-none">
    <div class="max-w-7xl flex flex-col z-10">
      <img src="~/assets/logo.svg" class="max-w-28" alt="" />
      <div class="text-4xl my-6 font-semibold !text-primary px-0">
        <span :class="{ 'pr-1': locale !== 'zh' }">{{ t('Rust-based') }} </span>
        <FlipWords :words="[t('High Performance'), t('Infinite Scaling'), t('Secure & Reliable'), t('Multi-Cloud Storage'), t('S3 Compatible')]" :duration="3000"
          class="text-4xl font-semibold !text-primary px-0" />
        <div class="text-muted-foreground mt-2">
          {{ t('Reliable distributed file system') }}
        </div>
      </div>
    </div>
    <a href="https://www.rustfs.com" class="z-10 text-primary-500 inline-flex w-max items-center gap-2 leading-none p-2 px-5 border rounded-full border-blue-500">
      <span>{{ t('Visit website') }}</span>
      <Icon name="ri:arrow-right-long-fill" class="mr-2" />
    </a>
    <div class="h-full inset-0 absolute z-0">
      <img src="~/assets/backgrounds/ttten.svg" class="absolute h-full w-full inset-0 z-0 opacity-45 object-cover" alt="" />
    </div>
  </div>
</template>

<script lang="ts" setup>
import { useI18n } from 'vue-i18n'
import FlipWords from '~/components/ui/flip-words/FlipWords.vue'

const { t, locale } = useI18n()
</script>
