// components/tiers/change-key.tsx
"use client"

import * as React from "react"
import { useTranslation } from "react-i18next"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import {
  Dialog,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog"
import { Field, FieldContent, FieldLabel } from "@/components/ui/field"
import { useTiers } from "@/hooks/use-tiers"
import { useMessage } from "@/lib/feedback/message"

interface TiersChangeKeyProps {
  open: boolean
  onOpenChange: (open: boolean) => void
  tierName: string
  onSuccess?: () => void
}

export function TiersChangeKey({
  open,
  onOpenChange,
  tierName,
  onSuccess,
}: TiersChangeKeyProps) {
  const { t } = useTranslation()
  const message = useMessage()
  const { updateTiers } = useTiers()

  const [accessKey, setAccessKey] = React.useState("")
  const [secretKey, setSecretKey] = React.useState("")
  const [submitting, setSubmitting] = React.useState(false)

  React.useEffect(() => {
    if (open) {
      setAccessKey("")
      setSecretKey("")
    }
  }, [open])

  const closeModal = () => {
    onOpenChange(false)
    setSubmitting(false)
    setAccessKey("")
    setSecretKey("")
  }

  const submitForm = async () => {
    if (!accessKey || !secretKey) {
      message.error(t("Please fill in the correct format"))
      return
    }
    setSubmitting(true)
    try {
      await updateTiers(tierName, {
        accessKey,
        secretKey,
      })
      message.success(t("Update Success"))
      onSuccess?.()
      closeModal()
    } catch (error) {
      message.error(
        (error as Error).message || t("Update Failed")
      )
    } finally {
      setSubmitting(false)
    }
  }

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-md">
        <DialogHeader>
          <DialogTitle>
            {t("Update Key")}：{tierName}
          </DialogTitle>
        </DialogHeader>
        <div className="space-y-4">
          <Field>
            <FieldLabel>{t("Access Key")}</FieldLabel>
            <FieldContent>
              <Input
                value={accessKey}
                onChange={(e) => setAccessKey(e.target.value)}
                placeholder={t("Please enter Access Key")}
                autoComplete="off"
              />
            </FieldContent>
          </Field>

          <Field>
            <FieldLabel>{t("Secret Key")}</FieldLabel>
            <FieldContent>
              <Input
                value={secretKey}
                onChange={(e) => setSecretKey(e.target.value)}
                type="password"
                placeholder={t("Please enter Secret Key")}
                autoComplete="off"
              />
            </FieldContent>
          </Field>
        </div>
        <DialogFooter>
          <Button variant="outline" onClick={closeModal}>
            {t("Cancel")}
          </Button>
          <Button onClick={submitForm} disabled={submitting}>
            {t("Submit")}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  )
}

// components/tiers/change-key.vue
<template>
  <Modal v-model="visibleProxy" :title="t('Update Key') + '：' + nameProxy" size="md" :close-on-backdrop="false">
    <div class="space-y-4">
      <Field>
        <FieldLabel>{{ t('Access Key') }}</FieldLabel>
        <FieldContent>
          <Input v-model="formModel.accessKey" :placeholder="t('Please enter Access Key')" autocomplete="off" />
        </FieldContent>
      </Field>

      <Field>
        <FieldLabel>{{ t('Secret Key') }}</FieldLabel>
        <FieldContent>
          <Input v-model="formModel.secretKey" type="password" autocomplete="off" :placeholder="t('Please enter Secret Key')" />
        </FieldContent>
      </Field>
    </div>

    <template #footer>
      <div class="flex justify-end gap-2">
        <Button variant="outline" @click="closeModal()">{{ t('Cancel') }}</Button>
        <Button variant="default" :loading="submitting" @click="submitForm">{{ t('Submit') }}</Button>
      </div>
    </template>
  </Modal>
</template>

<script setup lang="ts">
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'

import { Field, FieldContent, FieldLabel } from '@/components/ui/field'
import { computed, reactive, ref, watch } from 'vue'
import { useI18n } from 'vue-i18n'
import Modal from '~/components/modal.vue'

const { t } = useI18n()
const message = useMessage()
const usetier = useTiers()

const props = defineProps<{
  visible: boolean
  name: string
}>()

const emit = defineEmits<{
  (e: 'update:visible', visible: boolean): void
  (e: 'update:name', name: string): void
  (e: 'search'): void
}>()

const visibleProxy = computed({
  get: () => props.visible,
  set: value => emit('update:visible', value),
})

const nameProxy = computed({
  get: () => props.name,
  set: value => emit('update:name', value),
})

const formModel = reactive({
  accessKey: '',
  secretKey: '',
})

const submitting = ref(false)

watch(
  () => props.visible,
  value => {
    if (value) {
      formModel.accessKey = ''
      formModel.secretKey = ''
    }
  }
)

const closeModal = () => {
  emit('update:visible', false)
  submitting.value = false
  formModel.accessKey = ''
  formModel.secretKey = ''
}

const submitForm = async () => {
  if (!formModel.accessKey || !formModel.secretKey) {
    message.error(t('Please fill in the correct format'))
    return
  }
  submitting.value = true
  try {
    await usetier.updateTiers(props.name, {
      accessKey: formModel.accessKey,
      secretKey: formModel.secretKey,
    })
    message.success(t('Update Success'))
    emit('search')
    closeModal()
  } catch (error: any) {
    message.error(error?.message || t('Update Failed'))
  } finally {
    submitting.value = false
  }
}
</script>
