// components/user-group/edit-form.vue
<template>
  <Modal v-model="visible" :title="group.name || t('Members')" size="lg" :close-on-backdrop="false">
    <div class="space-y-4">
      <div class="flex items-center justify-between rounded-md border px-3 py-2">
        <span class="text-sm text-muted-foreground">{{ t('Status') }}</span>
        <Switch v-model:checked="statusBoolean" />
      </div>

      <Tabs v-model="activeTab" class="flex flex-col gap-4">
        <TabsList class="w-full justify-start overflow-x-auto">
          <TabsTrigger value="users">{{ t('Members') }}</TabsTrigger>
          <TabsTrigger value="policy">{{ t('Policies') }}</TabsTrigger>
        </TabsList>

        <TabsContent value="users" class="mt-0">
          <users-group-members :group="group" @search="getGroupData(group.name)" />
        </TabsContent>
        <TabsContent value="policy" class="mt-0">
          <users-group-policies :group="group" @search="getGroupData(group.name)" />
        </TabsContent>
      </Tabs>
    </div>
  </Modal>
</template>

<script setup lang="ts">
import { Switch } from '@/components/ui/switch'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { computed, ref } from 'vue'
import { useI18n } from 'vue-i18n'
import Modal from '~/components/modal.vue'

const { t } = useI18n()
const visible = ref(false)
const activeTab = ref('users')
const { getGroup, updateGroupStatus } = useGroups()

interface GroupInfo {
  name: string
  members: string[]
  status: string
}

const group = ref<GroupInfo>({
  name: '',
  members: [],
  status: 'enabled',
})

const statusBoolean = computed({
  get: () => group.value.status === 'enabled',
  set: async value => {
    const nextStatus = value ? 'enabled' : 'disabled'
    if (nextStatus !== group.value.status) {
      await handleGroupStatusChange(nextStatus)
    }
  },
})

const handleGroupStatusChange = async (status: string) => {
  await updateGroupStatus(group.value.name, { ...group.value, status })
  await getGroupData(group.value.name)
}

async function openDialog(row: any) {
  await getGroupData(row.name)
  activeTab.value = 'users'
  visible.value = true
}

async function getGroupData(name: string) {
  group.value = await getGroup(name)
}

defineExpose({
  openDialog,
})
</script>

// components/user-group/edit-form.tsx
"use client"

import * as React from "react"
import { useTranslation } from "react-i18next"
import { Switch } from "@/components/ui/switch"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { useGroups } from "@/hooks/use-groups"
import { UserGroupMembers } from "./members"
import { UserGroupPolicies } from "./policies"

interface GroupInfo {
  name: string
  members: string[]
  status: string
  policy?: string
}

interface UserGroupEditFormProps {
  open: boolean
  onOpenChange: (open: boolean) => void
  row: { name: string } | null
  onSuccess: () => void
}

export function UserGroupEditForm({ open, onOpenChange, row, onSuccess }: UserGroupEditFormProps) {
  const { t } = useTranslation()
  const { getGroup, updateGroupStatus } = useGroups()

  const [group, setGroup] = React.useState<GroupInfo>({
    name: "",
    members: [],
    status: "enabled",
  })
  const [activeTab, setActiveTab] = React.useState("users")
  const [statusBoolean, setStatusBoolean] = React.useState(true)

  const getGroupData = React.useCallback(
    async (name: string) => {
      const data = (await getGroup(name)) as GroupInfo
      setGroup(data)
    },
    [getGroup],
  )

  React.useEffect(() => {
    if (open && row?.name) {
      getGroupData(row.name)
      setActiveTab("users")
    }
  }, [open, row?.name, getGroupData])

  React.useEffect(() => {
    setStatusBoolean(group.status === "enabled")
  }, [group.status])

  const handleGroupStatusChange = async (status: string) => {
    if (status === group.status) return
    await updateGroupStatus(group.name, { ...group, status })
    await getGroupData(group.name)
    onSuccess()
  }

  const handleStatusToggle = async (checked: boolean) => {
    const nextStatus = checked ? "enabled" : "disabled"
    try {
      await handleGroupStatusChange(nextStatus)
    } catch {
      setStatusBoolean(group.status === "enabled")
    }
  }

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-lg" onPointerDownOutside={(e) => e.preventDefault()}>
        <DialogHeader>
          <DialogTitle>{group.name || t("Members")}</DialogTitle>
        </DialogHeader>
        <div className="space-y-4">
          <div className="flex items-center justify-between rounded-md border px-3 py-2">
            <span className="text-sm text-muted-foreground">{t("Status")}</span>
            <Switch checked={statusBoolean} onCheckedChange={handleStatusToggle} />
          </div>

          <Tabs value={activeTab} onValueChange={setActiveTab} className="flex flex-col gap-4">
            <TabsList className="justify-start overflow-x-auto">
              <TabsTrigger value="users">{t("Members")}</TabsTrigger>
              <TabsTrigger value="policy">{t("Policies")}</TabsTrigger>
            </TabsList>

            <TabsContent value="users" className="mt-0">
              <UserGroupMembers group={group} onSearch={() => getGroupData(group.name)} />
            </TabsContent>
            <TabsContent value="policy" className="mt-0">
              <UserGroupPolicies group={group} onSearch={() => getGroupData(group.name)} />
            </TabsContent>
          </Tabs>
        </div>
      </DialogContent>
    </Dialog>
  )
}
