// components/users/group/members.vue
<template>
  <div class="space-y-4">
  <Card class="shadow-none">
      <CardContent class="space-y-4 pt-6">
        <div v-if="!editStatus" class="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
          <div class="w-full sm:max-w-xs">
            <SearchInput v-model="searchTerm" :placeholder="t('Search User')" clearable class="w-full" />
          </div>
          <Button type="button" variant="secondary" class="inline-flex items-center gap-2" @click="startEditing">
            <Icon class="size-4" name="ri:add-line" />
            {{ t('Edit User') }}
          </Button>
        </div>
        <div v-else class="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between">
          <div class="flex w-full flex-col gap-2">
            <Label class="text-sm font-medium">{{ t('Select user group members') }}</Label>
            <Popover v-model:open="memberSelectorOpen">
              <PopoverTrigger as-child>
                <Button
                  type="button"
                  variant="outline"
                  class="min-h-10 justify-between gap-2"
                  :aria-label="t('Select user group members')"
                >
                  <span class="truncate">
                    {{
                      selectedUserLabels.length
                        ? selectedUserLabels.join(', ')
                        : t('Select user group members')
                    }}
                  </span>
                  <Icon class="size-4 text-muted-foreground" name="ri:arrow-down-s-line" />
                </Button>
              </PopoverTrigger>
              <PopoverContent class="w-72 p-0" align="start">
                <Command>
                  <CommandInput :placeholder="t('Search User')" />
                  <CommandList>
                    <CommandEmpty>{{ t('No Data') }}</CommandEmpty>
                    <CommandGroup>
                      <CommandItem
                        v-for="option in users"
                        :key="option.value"
                        :value="option.label"
                        @select="() => toggleMember(option.value)"
                      >
                        <Icon
                          name="ri:check-line"
                          class="mr-2 size-4"
                          :class="members.includes(option.value) ? 'opacity-100' : 'opacity-0'"
                        />
                        <span>{{ option.label }}</span>
                      </CommandItem>
                    </CommandGroup>
                  </CommandList>
                </Command>
              </PopoverContent>
            </Popover>
            <div v-if="members.length" class="flex flex-wrap gap-2">
              <Badge v-for="value in members" :key="value" variant="secondary">{{ value }}</Badge>
            </div>
          </div>
          <div class="flex items-center gap-2 sm:self-start">
            <Button type="button" variant="secondary" @click="changeMembers">{{ t('Submit') }}</Button>
          </div>
        </div>
      </CardContent>
    </Card>

    <Table class="overflow-hidden rounded-lg border">
      <TableHeader>
        <TableRow>
          <TableHead>{{ t('Name') }}</TableHead>
        </TableRow>
      </TableHeader>
      <TableBody v-if="filteredMembers.length">
        <TableRow v-for="member in filteredMembers" :key="member">
          <TableCell class="font-medium">{{ member }}</TableCell>
        </TableRow>
      </TableBody>
      <TableBody v-else>
        <TableRow>
          <TableCell class="text-center" colspan="1">
            <p class="py-6 text-sm text-muted-foreground">{{ t('No Data') }}</p>
          </TableCell>
        </TableRow>
      </TableBody>
    </Table>
  </div>
</template>

<script setup lang="ts">
import { Icon } from '#components'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent } from '@/components/ui/card'
import { Command, CommandEmpty, CommandGroup, CommandInput, CommandItem, CommandList } from '@/components/ui/command'
import { Label } from '@/components/ui/label'
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'
import { computed, onMounted, ref, watch } from 'vue'
import { useI18n } from 'vue-i18n'

interface UserOption {
  label: string
  value: string
}

const props = defineProps<{
  group: {
    name: string
    members: string[]
  }
}>()

const emit = defineEmits<{ (e: 'search'): void }>()

const { listUsers } = useUsers()
const { updateGroupMembers } = useGroups()
const { t } = useI18n()

const message = useMessage()

const editStatus = ref(false)
const searchTerm = ref('')
const memberSelectorOpen = ref(false)

const users = ref<UserOption[]>([])
const members = ref<string[]>([])

const userLabelMap = computed(() => {
  return users.value.reduce<Record<string, string>>((acc, option) => {
    acc[option.value] = option.label
    return acc
  }, {})
})

const selectedUserLabels = computed(() => members.value.map(value => userLabelMap.value[value] ?? value))

const filteredMembers = computed(() => {
  const keyword = searchTerm.value.trim().toLowerCase()
  const source = props.group?.members ?? []
  if (!keyword) return source
  return source.filter(item => item.toLowerCase().includes(keyword))
})

watch(
  () => props.group.members,
  newMembers => {
    members.value = [...(newMembers ?? [])]
    if (!newMembers?.length) {
      memberSelectorOpen.value = false
    }
  },
  { immediate: true }
)

const getUserList = async () => {
  try {
    const res = await listUsers()
    users.value = Object.entries(res ?? {}).map(([username, info]) => ({
      label: username,
      value: username,
      ...(typeof info === 'object' ? info : {}),
    }))
  }
  catch (error) {
    message.error(t('Failed to get data'))
  }
}

onMounted(() => {
  getUserList()
})

const startEditing = () => {
  members.value = [...(props.group.members ?? [])]
  memberSelectorOpen.value = false
  editStatus.value = true
}

watch(
  () => props.group.name,
  () => {
    editStatus.value = false
    memberSelectorOpen.value = false
  }
)

const toggleMember = (value: string) => {
  if (members.value.includes(value)) {
    members.value = members.value.filter(item => item !== value)
  }
  else {
    members.value = [...members.value, value]
  }
}

const changeMembers = async () => {
  try {
    const currentMembers = props.group.members ?? []
    const nowRemoveMembers = currentMembers.filter(item => !members.value.includes(item))

    if (nowRemoveMembers.length) {
      await updateGroupMembers({
        group: props.group.name,
        members: nowRemoveMembers,
        isRemove: true,
        groupStatus: 'enabled',
      })
    }

    await updateGroupMembers({
      group: props.group.name,
      members: members.value,
      isRemove: false,
      groupStatus: 'enabled',
    })

    message.success('修改成功')
    editStatus.value = false
    memberSelectorOpen.value = false
    emit('search')
  }
  catch (error) {
    message.error('修改失败')
  }
}
</script>

// components/user-group/members.tsx
"use client"

import * as React from "react"
import { useTranslation } from "react-i18next"
import { RiAddLine } from "@remixicon/react"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { Card, CardContent } from "@/components/ui/card"
import { SearchInput } from "@/components/search-input"
import { DataTable } from "@/components/data-table/data-table"
import { useDataTable } from "@/hooks/use-data-table"
import { UserSelector } from "@/components/user/selector"
import { useGroups } from "@/hooks/use-groups"
import { useMessage } from "@/lib/feedback/message"
import type { ColumnDef } from "@tanstack/react-table"

interface MemberItem {
  name: string
}

interface UserGroupMembersProps {
  group: { name: string; members?: string[] }
  onSearch: () => void
}

export function UserGroupMembers({ group, onSearch }: UserGroupMembersProps) {
  const { t } = useTranslation()
  const message = useMessage()
  const { updateGroupMembers } = useGroups()

  const [editStatus, setEditStatus] = React.useState(false)
  const [searchTerm, setSearchTerm] = React.useState("")
  const [members, setMembers] = React.useState<string[]>([])

  const membersData = React.useMemo<MemberItem[]>(
    () => (group?.members ?? []).map((name) => ({ name })),
    [group?.members],
  )

  const columns: ColumnDef<MemberItem>[] = React.useMemo(
    () => [
      {
        id: "name",
        header: () => t("Name"),
        cell: ({ row }) => <span className="font-medium">{row.original.name}</span>,
      },
    ],
    [t],
  )

  const { table } = useDataTable<MemberItem>({
    data: membersData,
    columns,
    getRowId: (row) => row.name,
  })

  React.useEffect(() => {
    const col = table.getColumn("name")
    if (col) col.setFilterValue(searchTerm || undefined)
  }, [searchTerm, table])

  React.useEffect(() => {
    setMembers([...(group?.members ?? [])])
  }, [group?.members])

  React.useEffect(() => {
    setEditStatus(false)
  }, [group?.name])

  const startEditing = () => {
    setMembers([...(group?.members ?? [])])
    setEditStatus(true)
  }

  const changeMembers = async () => {
    try {
      const currentMembers = group?.members ?? []
      const nowRemoveMembers = currentMembers.filter((item) => !members.includes(item))

      if (nowRemoveMembers.length) {
        await updateGroupMembers({
          group: group.name,
          members: nowRemoveMembers,
          isRemove: true,
          groupStatus: "enabled",
        })
      }

      await updateGroupMembers({
        group: group.name,
        members,
        isRemove: false,
        groupStatus: "enabled",
      })

      message.success(t("Edit Success"))
      setEditStatus(false)
      onSearch()
    } catch {
      message.error(t("Edit Failed"))
    }
  }

  return (
    <div className="space-y-4">
      <Card className="shadow-none">
        <CardContent className="space-y-4 pt-6">
          {!editStatus ? (
            <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
              <div className="w-full sm:max-w-xs">
                <SearchInput
                  value={searchTerm}
                  onChange={setSearchTerm}
                  placeholder={t("Search User")}
                  clearable
                  className="w-full"
                />
              </div>
              <Button type="button" variant="outline" className="inline-flex items-center gap-2" onClick={startEditing}>
                <RiAddLine className="size-4" aria-hidden />
                {t("Edit User")}
              </Button>
            </div>
          ) : (
            <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between">
              <div className="flex w-full flex-col gap-2">
                <UserSelector
                  value={members}
                  onChange={setMembers}
                  label={t("Select user group members")}
                  placeholder={t("Select user group members")}
                />
              </div>
              <div className="flex items-center gap-2 sm:self-end">
                <Button type="button" variant="outline" onClick={changeMembers}>
                  {t("Submit")}
                </Button>
              </div>
            </div>
          )}
        </CardContent>
      </Card>
      {editStatus && members.length > 0 && (
        <div className="flex flex-wrap gap-2">
          {members.map((v) => (
            <Badge key={v} variant="secondary">
              {v}
            </Badge>
          ))}
        </div>
      )}
      <DataTable table={table} />
    </div>
  )
}
