// pages/site-replication/index.vue
<template>
  <page>
    <page-header>
      <h1 class="text-2xl font-bold">{{ t('Site Replication') }}</h1>
    </page-header>
    <div class="flex flex-col gap-4">
      <div class="flex justify-end">
        <Button type="button" variant="outline" class="inline-flex items-center gap-2" @click="openForm">
          <Icon name="ri:add-line" class="size-4" />
          <span>{{ t('Add Site') }}</span>
        </Button>
      </div>

      <Card class="min-h-[400px] shadow-none">
        <CardContent class="flex h-full items-center justify-center">
          <p class="text-sm text-muted-foreground">{{ t('No Data') }}</p>
        </CardContent>
      </Card>

      <site-replication-new-form ref="addFormRef"></site-replication-new-form>
    </div>
  </page>
</template>

<script lang="ts" setup>
import { Icon } from '#components'
import { Button } from '@/components/ui/button'
import { Card, CardContent } from '@/components/ui/card'
import { ref } from 'vue'
import { useI18n } from 'vue-i18n'

const { t } = useI18n()
const addFormRef = ref<{ open: () => void } | null>(null)

const openForm = () => {
  addFormRef.value?.open()
}
</script>

// app/(dashboard)/site-replication/page.tsx
"use client";

import * as React from "react";
import { useState } from "react";
import { useTranslation } from "react-i18next";
import { RiAddLine } from "@remixicon/react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Page } from "@/components/page";
import { PageHeader } from "@/components/page-header";
import { SiteReplicationNewForm } from "@/components/site-replication/new-form";

export default function SiteReplicationPage() {
  const { t } = useTranslation();
  const [newFormOpen, setNewFormOpen] = useState(false);

  return (
    <Page>
      <PageHeader
        actions={
          <Button
            type="button"
            variant="outline"
            className="inline-flex items-center gap-2"
            onClick={() => setNewFormOpen(true)}
          >
            <RiAddLine className="size-4" aria-hidden />
            <span>{t("Add Site")}</span>
          </Button>
        }
      >
        <h1 className="text-2xl font-bold">{t("Site Replication")}</h1>
      </PageHeader>

      <div className="flex flex-col gap-4">
        <Card className="min-h-[400px] shadow-none">
          <CardContent className="flex h-full items-center justify-center">
            <p className="text-sm text-muted-foreground">{t("No Data")}</p>
          </CardContent>
        </Card>
      </div>

      <SiteReplicationNewForm
        open={newFormOpen}
        onOpenChange={setNewFormOpen}
      />
    </Page>
  );
}
